### ISSUE TITLE
Adding <rotation> section in vertical games MRA

### ISSUE THREAD

**Issue by capitaineflam25** [jotego/jtcores#117]
It would help managing OSD orientation if rotation can be read from MRA like on other cores 👍 

`<rotation>vertical (cw)</rotation>`

**Comment by capitaineflam25** [comment]
Concerned games are : 

1942 - vertical (cw)
1943 The Battle of Midway - vertical (cw)
Commando - vertical (cw)
Exed Exes - vertical (cw)
Gun Smoke - vertical (cw)
Legendary Wings - vertical (cw)
The Speed Rumbler - vertical (ccw)
Vulgus - vertical (cw)

**Comment by jotego** [comment]
This is ready in the source code now. I will push the changes to JTBIN later this month.

**Comment by jotego** [comment]
- [X] 1942
- [X] 1943
- [X] Commando
- [X] Exed Exes
- [X] Gun Smoke
- [X] Legendary Wings
- [X] The Speed Rumbler
- [X] Vulgus

Fixed in https://github.com/jotego/jtbin/commit/9775f01e64f990d07535e6241f7786743f179422
