### ISSUE TITLE
Block Block (Japan 910910) - issue with nvm file - settings not saved

### ISSUE THREAD

**Issue by wwark** [jotego/jtcores#128]
The nvm file for Block Block is correctly saved on the SD Card (/media/fat/config/nvram) when we save settings.

I applied the flip option in service mode. It is applied correctly and I saved the nvm file with "save settings".
But after restart the core, the option flip is not correct and if I come back to the service mode, the settings is not ok.

So to flip the screen in service mode, I need to do it at each start of the core.

Thanks,

**Comment by jotego** [comment]
confirmed in public version v1.2.9

**Comment by jotego** [comment]
This is fixed in the current version 74f67e48
To be released this week
