### ISSUE TITLE
dd: Music issues in Double Dragon core

### ISSUE THREAD

**Issue by ghost** [jotego/jtcores#132]
- In the first stage, when a character pops through the bricks wall the music cuts out and then it goes back to normal. 

- Music from the first boss ("The Entrance of Abobo the Giant" track) doesn't sound right from second ~10 or so.

**Comment by jotego** [comment]
Fixing the decay rate in https://github.com/jotego/jt51/pull/24 did not change change this issue.

**Comment by jotego** [comment]
I need a more clear case to study this. The issue is too subtle.
