### ISSUE TITLE
mikie: unused filters

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#136]
The filter-control signals are ignored. It isn't clear whether these are mute signals or a change in the bandwidth of a LPF

https://github.com/jotego/jtkicker/blob/a935e94262a01129a1d61d6f8c446c7acc3709cd/cores/mikie/hdl/jtmikie_snd.v#L78

**Comment by jotego** [comment]
@etriana85 unsolder one of the Konami switches and measure it on a protoboard for characterization. 
I think it is an analog switch, so there will be two input/output pins and one control pin. The control pin will set the impedance across the other two pins.
- When the control is low, the impedance (resistance) will be high
- When the control is high, the impedance will be low
Or vice versa, it may be that when the control is high, the impedance is high.

Tasks
- [ ] Unsolder a device from one of the Konami boards that have it
- [ ] Apply 5V and GND to the same pins as in the original board
- [ ] Apply 0V to the control pin and measure the resistance across
- [ ] Repeat with 5V applied to the control pin
- [ ] Resolder the device to the original board. Use a socket if possible

**Comment by etriana85** [comment]
![HM4066_test](https://user-images.githubusercontent.com/92724765/224293575-ef07a3ef-7450-4668-b25d-cb3a8d069281.jpg)
![medidas_4066](https://user-images.githubusercontent.com/92724765/224297566-5be86725-211e-4a74-a0af-a63a3bd1e0b2.png)

**Comment by etriana85** [comment]
![HM4066_test](https://user-images.githubusercontent.com/92724765/224299736-1f247fe9-0dcd-4b18-8c8a-6d432f8b30f2.jpg)
![test_4066](https://user-images.githubusercontent.com/92724765/224299742-5d64e72b-9213-4809-bf9b-be6ef6e7861c.png)

**Comment by etriana85** [comment]
![4066-test](https://user-images.githubusercontent.com/92724765/224326469-77af163e-6cc8-483a-bde4-8aac32b99d1c.png)
![HM4066_test](https://user-images.githubusercontent.com/92724765/224326505-441be37c-550e-4055-9541-b1dc061b3db8.jpg)

**Comment by jotego** [comment]
the switch is on when the control input is high
![imagen](https://github.com/jotego/jtcores/assets/1863036/db622f48-964b-4d68-9b32-b1a9cf297cbe)
