### ISSUE TITLE
CPS3 Custom chips

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#154]
Obtain die pictures of the custom chips

- [x] Obtain disposable custom chips
- [x] Desolder
- [x] Decap
- [x] Die pictures
- [x] Upload and share with interested developers

**Comment by jotego** [comment]
@etriana85 download die pictures from [here](https://siliconpr0n.org/archive/doku.php?id=tag:vendor_capcom&do=showtag&tag=vendor_capcom)

**Comment by etriana85** [comment]
cps3 custom chip internal tracking.
![DL-3529-GLL2](https://user-images.githubusercontent.com/92724765/230603099-54661d2b-f14b-42bf-a57c-361c8bd4b84b.png)
