### ISSUE TITLE
CPS1 Original-filter comparison with PCB

### ISSUE THREAD

**Issue by paulb-nl** [jotego/jtcores#156]
Here is a video recorded from jtcps1 20210201 with filter enabled.
https://youtu.be/HNkTJRo_ZR0

Here are videos of the pcb:
https://youtu.be/4C1vcIH7FTA

https://youtu.be/EDXE0SsaCiM

Doesn't it sound like the filter is removing too much high frequency compared to the pcb? The cymbal and drum sound very muffled.

**Comment by LordBarker80** [comment]
Appreciate this is an old issue but the same issue is present in Final Fight audio-wise.

**Comment by h1deous** [comment]
Also, Captain Commando and others.

**Comment by jotego** [comment]
Completed in 612104bd
