### ISSUE TITLE
s16b: e-swat FD1094 317-131: fast paced samples

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#160]
From _Masked Ninja_ in Discord:

> The Japanese version of E-Swat FD1094 317-131 works well, except for the sound samples in conversations that are fast-paced, like the hostage girl saying "Oh, thank you officer...!".

**Comment by florgana** [comment]
I can't reproduce the problem. Review ID **ee3afab5**, there the recovery was updated maybe it has been solved
