### ISSUE TITLE
shanon: band in the middle of the road

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#165]
commit: 831a6bc

There is a transparent band in the middle of the road. It looks like it should overlap with the road markings and not be transparent.

![20221126_081646-screen](https://user-images.githubusercontent.com/1863036/204079363-2b9eeee3-d6f7-4576-b668-1d83eb168104.png)

**Comment by jotego** [comment]
The problem occurs because the _cent_ signal (centre) is not aligned with the road bitmap centre. Thus, the road layer type (sky, ground, etc.) signal _rrc_ carries the wrong information around the centre of the road

![imagen](https://github.com/jotego/jtcores/assets/1863036/438f44d9-3b1b-4553-b16c-1a07ae0d1d16)

**Comment by asturur** [comment]
will this fix also outrun similar lines? or cores are different enough for that not to be the case?

**Comment by jotego** [comment]
Yes, it fixes both cores.

**Comment by asturur** [comment]
tried this and looks great, outrun finally without the line in the middle is great.
