### ISSUE TITLE
s16b: Passing Shot (4P version): 1P controls both 1P and 2P, 3P & 4P aren't registered

### ISSUE THREAD

**Issue by KremlingKuthroat19** [jotego/jtcores#169]
The standard 2P Passing Shot MRA works perfectly.

This version has issues: Passing Shot (Japan, 4p, S16A) [FD1094 317-0071].mra

The issues are that 1P maps to both 1P and 2P so 1P controls both players. Also, 3P and 4P's controls don't register so the game only works as a 2P game, not a 3P or 4P game.

**Comment by florgana** [comment]
This issue is fixed. Passing Shot (Japan, 4p, S16A) [FD1094 317-0070]  the maps is correct.
