### ISSUE TITLE
s16b: Dunk Shot: 2P and 4P up and down controls reversed

### ISSUE THREAD

**Issue by KremlingKuthroat19** [jotego/jtcores#170]
When playing a 2P to 4P match, the second and fourth player's joysticks for up and down are reversed. Down goes up and up goes down. I'm assuming this is actually technically correct due to the game being a cocktail arcade cabinet. 

Can you add an option or just change the code to make 2P and 4P have the same movement as 1P and 3P, please? It'd make the game way more playable :)

**Comment by florgana** [comment]
The order of the controls for 2P and 4P was inverted, now it is the same as 1P and 3P
