### ISSUE TITLE
Golden Axe set 6 starts in test mode

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#171]
First identified in issue jotego/jts16#16. The MRA file did not change (other than comments). Occurs in MiST too. It occurs at least since version 21574e8

**Comment by florgana** [comment]
Bug fixed, version d842bd29

**Comment by jotego** [comment]
This was closed by mistake. It still occurs.

**Comment by jotego** [comment]
It looks like the relative reset-VB time is important to get the MCU initialized correctly before the main CPU starts processing interrupts. Fixing the time at which reset occurs seems to solve the issue.
For **tturf**, that doesn't work but it may be related to the custom firmware used. I have removed that ROM set for now until a MCU dump appears.
