### ISSUE TITLE
s16b E-SWAT: glitch prevents advancement on stage 9

### ISSUE THREAD

**Issue by ryanfb** [jotego/jtcores#172]
Loaded up E-SWAT (set 4, World), playing through with default DIP switches, I noticed that once I got to stage 9 and advanced there's a sequence where enemies on trucks are supposed to appear, however, the first one glitches out, the rest don't appear, and you wind up stuck and unable to advance on a screen with no enemies.

Here's how the sequence is supposed to go from an arcade LP: https://youtu.be/1Bk04N-0ZLM?t=503

**Comment by tcamargo** [comment]
Just replicated the problem with sets 3 and 4.

**Comment by florgana** [comment]
Fixed. 
The sign of the multiplier was changed, before was unsigned. Now the multiplier is signed.
