### ISSUE TITLE
s16b: cotton, graphic glitch, St.2 Moving background

### ISSUE THREAD

**Issue by Aquas77** [jotego/jtcores#173]
Example video: https://www.twitch.tv/videos/1273148483 (Glitch begins about 10 seconds into the video)

It appears that the moving background of the graveyard, in the latter half of Stage 2, causes a graphic glitch on that background effect which persists until the end of the stage. It is quite easy to pick out once you notice it.

On 32mb xs1.1 sorgelig sdram still, and just ran my update_all.

**Comment by jotego** [comment]
Fixed on 6e601450
Sorry for the long wait
