### ISSUE TITLE
CPS1 - Support for Magical Pumpkin

### ISSUE THREAD

**Issue by ajgowans** [jotego/jtcores#196]
Magical Pumpkin is a recently dumped short theme park game.  it actually runs on the core with the attached .mra file and the mame rom files (hkittymp).  I was able to play through, however the game is meant to use a steering wheel and it is not possible to move all the way to the left or right of the screen with a controller.  

Is it possible to fix so the controller can move the character all the way left and right (potentially add steering wheel support) and release the .mra as part of the core?

[Magical Pumpkin - Puroland de Daibouken (Japan 960712).mra.zip](https://github.com/jotego/jtcores/files/10808543/Magical.Pumpkin.-.Puroland.de.Daibouken.Japan.960712.mra.zip)

**Comment by jotego** [comment]
Thank you for the MRA file. I will look into it. It may be related to #150

**Comment by wwark** [comment]
Normally Magical Pumpkin used a wheel

**Comment by jotego** [comment]
- [X] Added MRA for Magical Pumpkin in https://github.com/jotego/jtcores/commit/64ab7603e110dd3a92c088c4619c7a0742dbfde7
- [ ] Add spinner support

**Comment by jotego** [comment]
The game with spinner support is available on JTBIN now.
