### ISSUE TITLE
Chelnov Public Release

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#200]
Pending actions from beta

**Graphics**
- [x] Score characters
- [x] Graphics are correct
- [ ] Flip mode

**FPGA**
- [x] Check Pocket

**Comment by davidromani** [comment]
First of all many thanks for your precious time & effort to make these cores so incredible. 

Probably this is **not** the right place to ask my doubt, my apologies, but I'm newbie with Mister FPGA and there are so much spreaded information that it's really hard to manage and understand at the begining.

When I try to play this core it seem's that there is a missing file error inside zip. Is this core only available for premium users? Or it's a problem with my instalation?

Thank you so much again and hope that in a future I can help or contribute to this amazing comunity.

![IMG_6560](https://github.com/jotego/jtcores/assets/698779/f015c65c-1b47-4aa2-938c-8d3d0d44cd55)

**Comment by jotego** [comment]
This core was made public several months ago after the beta phase supported by Patreon members.

The error you are getting is about the files in your ROM dump. You seem to be missing one file there. The core will most likely not work because of that missing file. Note that MAME may still work using that same zip archive because it usually does not need all the files as part of the game logic may be hard coded inside MAME.

**Comment by davidromani** [comment]
Thanks for your answer @jotego, you've clarify me some doubts. I'll keep investigating where this file must be located and why is missing.
