### ISSUE TITLE
Karnov video measurements

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#201]
Measure the following signals

- All signals from part 16A on lower PCB (HMC-20) except pins:
  - 2 (RST)
  - 3 (12MHz CLK)
  - 1 (test)
  - 28 (VCC)
  - 14,15 (VSS)

Information:
- [Schematics](https://www.gamesdatabase.org/Media/SYSTEM/Arcade/Manual/formated/Karnov_-_1987_-_Data_East.pdf)

**Comment by etriana85** [comment]
The monitor or video adapter sends a "No Signal" message.
The pcb doesn't work apparently.

**Comment by etriana85** [comment]
This pcb won't boot.
New Jotego instructions:
-Measure the CLK and CSYNC, (measurements are attached in images).
-Unsolder chip HMC20_60232_4Z01, location A16.
-Solder socket.
-Mount the CLK on protoboard according to Karnov sch design.
-Measure the output of the osc mounted on the protoboard. (I attach an image of said measurement, with the name of "CLK_test_Karnov"

**Comment by etriana85** [comment]
![CLK_HM20_Karnov](https://user-images.githubusercontent.com/92724765/223755693-162d55bd-dbe7-4dd7-aa65-15051cd992e9.jpg)
![CSYNC_Karnov](https://user-images.githubusercontent.com/92724765/223755701-ab317710-a9df-4f68-8a3d-9d64bbed5361.jpg)
[CSYNC_Karnov.webm](https://user-images.githubusercontent.com/92724765/223755704-8b8eb44a-6d34-4f53-ae38-dc31f783c307.webm)

**Comment by etriana85** [comment]
![CLK_test_Karnov](https://user-images.githubusercontent.com/92724765/223756108-4ed0043a-cc6c-4791-b8a3-3d43c7e0c62c.jpg)
![HM20](https://user-images.githubusercontent.com/92724765/223756114-edff0a28-84d1-452c-a307-6493c3a95a34.jpg)
![HM20_ext](https://user-images.githubusercontent.com/92724765/223756118-ae0d5109-c4ac-4a76-ab86-316757ca13a0.jpg)
![HM20_extside](https://user-images.githubusercontent.com/92724765/223756121-97e1157c-4def-4cf2-8f1c-7b6e8e36203a.jpg)
![HM20_zoc](https://user-images.githubusercontent.com/92724765/223756125-e9162a30-6aeb-4a8a-b712-145483e29dc0.jpg)
![HMC20_60232_4Z01](https://user-images.githubusercontent.com/92724765/223756128-cf971200-72e1-4fe6-8c7b-5a4068adaa77.jpg)
![zocaloHM20](https://user-images.githubusercontent.com/92724765/223756133-ab9c1ebf-50eb-404a-9662-6a33b83b95d2.jpg)

**Comment by etriana85** [comment]
Observation:
According to the shc, the CSYNC signal (pin 40 TC176042AF, location 12M) attacks pin 12 of an and gate (location 12E). When following it since the oscilloscope signal was not stable, I detected that said signal does not go out through pin 40, it goes out through pin 41.
Attached images of the sch.

![and_csync](https://user-images.githubusercontent.com/92724765/223761273-54b56a87-90b5-409e-8fc5-822781ede126.jpg)
![pin41_csync](https://user-images.githubusercontent.com/92724765/223761277-b5c0a8d4-a94c-43f4-bd3a-d1dc1590c8d8.jpg)

**Comment by etriana85** [comment]
By Jotego's instruction, the pcb will be prepared to be returned to Atrac17.
