### ISSUE TITLE
jtkiwi: sound issues (tnzs, the new zealand story)

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#211]
Sound codes 05 and 07 are reported to feel different. An FM instrument is reported to sound lower.

Reported by _Masked Ninja_ on Discord

**Comment by rogalian** [comment]
All audio in tnzs is a full octave lower than original hardware.

**Comment by rogalian** [comment]
I can't get a direct recording, but I can take a video with a phone?

(MAME audio is correct)

**Comment by Toryalai1** [comment]
It is better if it is a direct recording

**Comment by rogalian** [comment]
https://github.com/jotego/jtcores/assets/5140184/19cb38c0-1c4f-4488-8db3-cc156ed12887

Best I can manage, should be clear.

**Comment by jotego** [comment]
The sound octave problem is fixed now. I think some sound effects may still feel different. If you can report a specific sound code in the test menu that fails for any of the games supported in the core, that will help.

**Comment by rogalian** [comment]
It's spot on now, thank you.
