### ISSUE TITLE
s16: move sound to 48MHz clock

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#216]
Required to enable RECOVERY on Z80
- [x] s16
- [x] s16b
- [x] shanon
- [x] outrun

**Comment by florgana** [comment]
@jotego Done. Here [58a1c0f](https://github.com/jotego/private/commit/58a1c0f657fd7e049e1c722152fa76d49b6a1751) and [940b723](https://github.com/jotego/private/commit/940b723f1091b1b1da9d51041f043ad4a271f209)
