### ISSUE TITLE
System 18: schematic misconnections

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#222]
@etriana85 check this for s18:

> On R3, Pin 8 is D3, not D10.
> 
> On Y6, four pins are mislabeled. They should be:
9 - AB8
7 - AB7
5 - AB6
3 - AB5

Original report [here](https://twitter.com/_ShootTheCore/status/1638433218033750016?s=20).

**Comment by etriana85** [comment]
After checking the connections, this has been corrected.
![issue#222](https://user-images.githubusercontent.com/92724765/226838585-1630f8d7-970b-4ee3-ac8c-bb20eb0884f2.png)
![issue_#222](https://user-images.githubusercontent.com/92724765/226838599-e5bd1403-9367-4e4d-9878-299c5d0a437d.png)
