### ISSUE TITLE
Konami 085

### ISSUE THREAD

**Issue by GavinAndrews** [jotego/jtcores#230]
FYI On a real Konami 085 the value produced on a pin 11 INTSHOW read is the vertical value not the scroll value loaded via pin 15.

I think that is what you suspected

**Comment by jotego** [comment]
Thank you. I wasn't able to determine whether it was the scroll value or the raster vertical position with my chip measurements. I have updated the code to read the vertical position.

https://github.com/jotego/jtcores/commit/197b482c3f591c173a49dfad2c8c2a895c9064a4
