### ISSUE TITLE
pocket: 19xx, Dimahoo, flip settings

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#233]
Apparently the image is upside down with the default settings

**Comment by YLFAndy** [comment]
Setting option 3 in cores/jotego.jtcps2/video.json to 270 fixes all of the flipped games and doesn't appear to impact any of the non-flipped ones. I haven't tested fully, but it solved the issue for me in 19XX and Dimahoo both and every other game I've tried has not had any negative impact.

**Comment by jotego** [comment]
Although it can fixed through the JSON file, this is actually related to missing the default values in the NVRAM as the beta version does not load them on the Pocket.

**Comment by jotego** [comment]
This seems to already be working on commit 1e5a4916. I am not sure which commit fixed it.

**Comment by jtmiki** [comment]
One patreon wrote this today that Dimahoo's screen orientation has changed abnormally again.

**Comment by jotego** [comment]
Everything seems fine in f8166fbb. It was a false alarm.
