### ISSUE TITLE
Golden Axe US Set 6 (default MRA) starts in Service Mode, no Test button mappable to exit.

### ISSUE THREAD

**Issue by YLFAndy** [jotego/jtcores#235]
As discussed on the Discord, this issue has previously been filed but was closed. The default Golden Axe MRA - Golden Axe (set 6, US) (8751 317-123A).mra - starts in Service Mode with no way to exit as the Test button is not wired up. 

Repro Steps:
Fresh MiSTer install
Update_all.sh with Arcade cores enabled
Launch the OSD and navigate to Arcade > Golden Axe (set 6, US) (8751 317-123A) in the main arcade list (alternates work)

Result: The core launches directly into Service Mode as if the DIP is thrown in the initial memory write.

Expected: The game to launch into standard mode with default settings if no other settings exist.

This can sometimes be worked around by toggling any DIP, then returning to the main core menu and toggling Service Mode quickly. 

https://youtu.be/zecEnmqrYUQ

**Comment by YLFAndy** [comment]
This is linked to https://github.com/jotego/jtcores/issues/171

Which was closed when I last looked at it but has been reopened, with no details apart from 'related to MCU core consolidation.'

**Comment by vanfanel** [comment]
I can confirm this issue is still happening (after a year or more) with latest core and US Set 6 roms.

**Comment by florgana** [comment]
duplicate in #171
