### ISSUE TITLE
Outrun: 1st OSD screen not displayed on MiSTer

### ISSUE THREAD

**Issue by suww37** [jotego/jtcores#240]
Outrun core dip switch option not working.

**Comment by jotego** [comment]
For some reason, the OSD screen showing DIP switches and other options is not displayed on MiSTer. Only the core switch screen gets shown. Seen in f925873f but it must have started much earlier than that.

**Comment by asturur** [comment]
Just an heads up i tried the lastest compiled core i found in the github action and this issue seems solved.
(the red car logo splash screen of outrun is now flashing red and blue pixels, but that could be my mister)

**Comment by jotego** [comment]
I guess you tried the version compiled by the GitHub action... thank you.

The OSD menu operation is restored in f43b2b5f. This bug was very weird. It might have been related to the relaxed timing constraints for the MiSTer framework used on some compilations.
