### ISSUE TITLE
Heavy Barrel - Title glitched graphics, freezes, sometimes resets at end of stage 1.

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jtcores#244]
Many times when I've tried Heavy Barrel's main mra in the Arcade folder on MiSTer (World version), the title does not display correctly, and if you insert a coin and try to start the game, it completely freezes.

When I was actually able to start the game, I had it reset to the title screen after completing stage 1.  This happened on my second time trying to play the game, with the first time making it to stage 3 with no issues (besides the game being ridiculously hard at parts... heh)

I've only tried the World version, and am unsure if alternates have the same behavior.

Example of the glitched title screen:
![untitled](https://user-images.githubusercontent.com/40709481/233294483-f8c7f10a-7c92-4aae-b918-3e44f05caf71.JPG)

**Comment by jotego** [comment]
Confirmed in version 900ecff

**Comment by jotego** [comment]
All fixed in 1b90229
Updating JTBIN at the moment
