### ISSUE TITLE
Super Street Fighter 2 Turbo Graphical issue when playing Akuma

### ISSUE THREAD

**Issue by wereoffs** [jotego/jtcores#248]
When selecting Akuma as a player in Super Street fighter 2 Turbo, there is a black box appearing on the left of the screen. 
(I don't know if it is a coincidence, but a similar bug happens randomly, but rendering random sprites in the same zone, this time when playing with Ryu.)
![akumabug](https://user-images.githubusercontent.com/107465990/233653202-00b6c3b6-8c26-45f9-99e7-71033ee192a8.jpg)

Reproductivity: 5/5

Steps to reproduce:
Launch Game
Insert coin
Press start (player 1)
Select/unlock Akuma character (using the right code sequence) ([https://twitter.com/victoralonso_es/status/1647729867755073536](https://twitter.com/victoralonso_es/status/1647729867755073536))

The black box appears during the fight gameplay,Win / lose /map scenes looks ok.

**Comment by wereoffs** [comment]
Oh, just found in the linked video that it happens as well in the original hardware, so not a core issue. sorry :D

**Comment by jotego** [comment]
Thank you for investigating this.
