### ISSUE TITLE
2nd player buttons not mapped in Cadillacs & Dinosaurs and Eco Fighters

### ISSUE THREAD

**Issue by christ776** [jotego/jtcores#250]
Whenever I want to enter the Service Mode in any of these games 

- Cadillacs & Dinosaurs 
- Eco Fighters
I have no way to exit of the Service Mode becaue it needs the 2nd player button (I believe it's the Start button) to exit. 

Thus having to reset the whole game.

**Comment by jotego** [comment]
It actually needs a special service button, which is not mapped to the controller. You will need to attach a keyboard and press F2. That's the same key than the one used in MAME for this.

It is cumbersome to map this and many other keys of little interest such as coin service or tilt. I prefer to keep it keyboard-only as a feature for advanced users.
