### ISSUE TITLE
cps3: wrong signal names

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#254]
Some schematics signal names are wrong. Reported by _Apocalypse_

- gfx_c and gfx_d should be SH2 bus
- gfx_a and gfx_b should be sound bus
- sprite_c and sprite_d should be backgrounds
- sprite_a and sprite_b are really the sprites

**Comment by etriana85** [comment]
I have corrected the names of the signals. Attached modification in chips and signals.
![1](https://user-images.githubusercontent.com/92724765/236249007-8035b2b2-ee42-4a9c-b1a0-1aada607fbc7.png)
![2](https://user-images.githubusercontent.com/92724765/236249045-3f60c827-00de-495e-a5fe-9969cec2cd63.png)
![3](https://user-images.githubusercontent.com/92724765/236249064-502cc767-30e0-4b61-8de3-822717885ba7.png)
![SCR_SPR](https://user-images.githubusercontent.com/92724765/236249123-21d7c4bc-188a-4fa1-9386-baddf38cf0d4.png)
![SCR_SPR_PPU](https://user-images.githubusercontent.com/92724765/236249158-04941153-7681-474d-81ea-34b67c1da673.png)
![SND_A-D](https://user-images.githubusercontent.com/92724765/236249185-b04220f5-cbd2-4b6b-9b61-5e064480b56a.png)
![SPR_A-AB](https://user-images.githubusercontent.com/92724765/236249221-bbc73b88-493d-423a-9b3b-4e429b3a8f0c.png)
![SND_S1-2](https://user-images.githubusercontent.com/92724765/236249253-4775e7d4-c916-4da6-a3f9-5464cc02681f.png)

**Comment by jotego** [comment]
Thank you
