### ISSUE TITLE
Rastan - certain sound effects not accurate

### ISSUE THREAD

**Issue by thelatestmodel** [jotego/jtcores#255]
Rastan's voice (jump sound, death sound) and the attack / weapon swing sound are not accurate to the arcade and need to be looked at.

His voice is way too deep, and the attack sound has kind of a deep metallic ring to it instead of the "chak" sound you hear in the arcade. Note that this is the weapon swing sound (i.e. swing and miss), NOT the sound that plays if your attack hits an enemy.

It is easy to hear the difference if you play the MAME version side by side.

**Comment by jotego** [comment]
The MSM5205 frequency was wrong by about 50% lower, so PCM effects sounded low. The updated files will be in JTBIN in a few minutes.
Thank you for reporting it.
