### ISSUE TITLE
s16b sound goes away

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#259]
This started happening around the repository consolidation. Music starts but quickly fades away forever. Some sound effects may be heard after that.

It could be related to the jt7759. 

The issue didn't change when cen generation was moved to mem.yaml

**Comment by florgana** [comment]
@jotego  this issues is fixed here [df8bf1d](https://github.com/jotego/private/commit/df8bf1d7b68be19e0485dcbc7f0144fef15fa248), I close it.
