### ISSUE TITLE
Cropped screen in jtdd,jtdd2,jtkunio on analogue pocket

### ISSUE THREAD

**Issue by SkyNIC** [jotego/jtcores#265]
On analogue pocket display game looks cropped 
![изображение](https://github.com/jotego/jtcores/assets/1808805/639771b9-45da-4429-a7f5-a5b5d327b5da)
![изображение](https://github.com/jotego/jtcores/assets/1808805/3cf9a5ba-daa4-4b69-8c50-ad600cf4b31d)
But if I made screenshot it looks fine on it
![20230511_182104](https://github.com/jotego/jtcores/assets/1808805/34c98f7c-2310-4ea8-98ec-ee83a3e5ffad)
![20230511_182123](https://github.com/jotego/jtcores/assets/1808805/baa0562a-3f15-4360-89b6-9a5bce8801ac)

**Comment by jotego** [comment]
I don't know what caused this but when tested on git commit 67256624, everything seems fine. I'll update the binary files.

**Comment by SkyNIC** [comment]
Issue still present on latest core versions. Only on Analogue Pocket screen. When it connected through the Dock or screenshot looks fine. 
jtdd.rbf_r (14C09E98)
ddragon.rom (3E995248)
jtdd2.rbf_r (9578E5EA)
ddragon2.rom (83D0E4B1)
jtkunio.rbf_r (0AC9BFA9)
kuniounb.rom (C4C204EF)
renegdeb.rom (2440E583)
