### ISSUE TITLE
Aliens: Random sprite corruption

### ISSUE THREAD

**Issue by djhardrich** [jotego/jtcores#267]
Video attached, look closely at the area around the Alien while Ripley is recovering.

Steps to reproduce: At the end of level one, get hit on purpose/fire while flashing after being hit. Corruption/displaying the wrong sprite generally manifests as a slice of the Alien's neck/head floating in space, Ripley's right or left side being replaced with the Alien's arms/legs every third frame (normal, alien, blank, repeat), or a sprite priority issue with the gunfire displaying on top of Ripley while she flashes.

https://github.com/jotego/jtcores/assets/22062445/4ab7d5b2-3e84-4298-ae00-1ad96db44276

**Comment by djhardrich** [comment]
Just tested in the new build (1.2.24), First Boss seems stable! Unfortunately, it crops up with Evil Newt and Alien-Bat Ripley in the subsequent stage if you get hit…

Evil Newt (Bottom Right):
![IMG_7112](https://github.com/jotego/jtcores/assets/22062445/ae0b85b2-b06d-435f-a7b9-c3820d7b2c74)

Alien-Bat Ripley:
![IMG_7111](https://github.com/jotego/jtcores/assets/22062445/e3f85f79-ab21-445e-828b-95666442875e)

**Comment by jotego** [comment]
Blast. No easy victory. That didn't happen before, did it?

**Comment by djhardrich** [comment]
Not to my knowledge (played that stage 3 times on previous build and didn’t see it); there’s also something a little off with scrolling on a crt; it’s as if there’s a 15% frameskip/slight judder happening, could possibly be related? I’ll open a separate issue with more info/relevant video captures; Aliens might be the only game I’ve spent more time playing in the arcade than Street Fighter II!

**Comment by jotego** [comment]
It looks like the status bit read by the CPU was inverted. Thus, the CPU was writting sprite data during blanking instead of during active video. Everything should work now well. I'm updating the files in a few minutes.
