### ISSUE TITLE
update to KiCAD 7.0

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#268]
@etriana85 let's upgrade to the new KiCAD this Friday.

**Comment by skutis** [comment]
It has some small bugs when running ERC. The ERC window closes when switching focus to an error in the schematic. But I haven't noticed anything else. The schematic process is less painful.

**Comment by jotego** [comment]
That may be intentional. I wonder if there is an option to keep it open.

**Comment by jotego** [comment]
@etriana85 updated all schematics  to KiCAD 7 last week
