### ISSUE TITLE
Service Menu / ROM Checks Fail / Grid Alignment [JTALIENS v1.2.29]

### ISSUE THREAD

**Issue by atrac17** [jotego/jtcores#272]
Thanks for working on Super Contra! Here's a few things I noticed after firing it up. ROM checks fail and service menu cannot be accessed by pressing 1P Start. Also, the reset line is still finnicky and can result in a red screen when attempting to access the service menu.

**[JTALIENS v1.2.29 Core Footage](https://youtu.be/z6-1iv2pE-8)**

**[MAME 0254 Footage](https://youtu.be/kN0i64Wokjs)**

Video grid isn't centered, a few rows of pixels are cut off (below). PCM audio doesn't always play, some sounds are muted in the mix. I'm unable to access the sound test to pursue this any further because you cannot cycle thru options after enabling service mode.

![grid](https://github.com/jotego/jtcores/assets/32810066/a6553d68-69fe-435e-bace-658cc42c429b)

https://github.com/jotego/jtcores/assets/32810066/b2d79a43-4fb6-4026-825a-16c82996ec54

If I notice any other issues, I'll report them. I don't remember if the vblank happens when you coin on the PCB. MAME and the core both do this. It's been awhile since I've played it on hardware. You might want to verify that with the PCB I loaned too.

**Comment by jotego** [comment]
The logic needed to check graphic ROMs is not implemented yet. It's the same problem in Aliens. That has low priority for now. The service menu will show bad ROMs for a while.

I fixed the PCM sounds problem. Thank you!

**Comment by jotego** [comment]
Action on ROM checks moved to #557
