### ISSUE TITLE
Add support for rotary stick

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#284]
- [The stick](https://misterfpga.org/viewtopic.php?p=69765#p69765)
- [Used in this repo](https://github.com/va7deo/SNK68)
- [Adaptor code](https://github.com/va7deo/SNK68/tree/main/dev/rp2040)

**Comment by jotego** [comment]
@atrac17 do you have news regarding this?

**Comment by atrac17** [comment]
> @atrac17 do you have news regarding this?

I'll get you something in the next day or so...
