### ISSUE TITLE
s16b: Measure the length of /VINT signal on SEGA System 16B

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#293]
Measure the length of /VINT signal, which is pin 55 of 315-5197

**Comment by etriana85** [comment]
Below I attach images with the requested measurements
![~VINT](https://github.com/jotego/jtcores/assets/92724765/453e1ba7-6073-4d9a-ae87-3d7cb45a4401)
![~VINT2](https://github.com/jotego/jtcores/assets/92724765/93692e27-09e4-4fd7-a1ce-03b9cc8104d4)
![~VINT_CSYNC](https://github.com/jotego/jtcores/assets/92724765/1ee7c190-4143-486a-a490-0e2b8ebad982)
![~VINT_CSYNC2](https://github.com/jotego/jtcores/assets/92724765/2383bb91-8c65-480d-abcb-5ee4215801b3)
![~VINT_HSYNC_VSYNC](https://github.com/jotego/jtcores/assets/92724765/77cdbc48-961f-4bbb-b5bd-a44ee5e92dc4)

**Comment by etriana85** [comment]
Others that may be of interest...
![S16 H freq](https://github.com/jotego/jtcores/assets/92724765/c9083ed7-114d-46de-9ba3-7c58eb232374)
![S16 H timing](https://github.com/jotego/jtcores/assets/92724765/54d4fe13-4529-4a15-84a9-d427066ffb76)
![S16 VBLANK](https://github.com/jotego/jtcores/assets/92724765/5baa0154-f456-4efb-94b8-c8dc5a255a4d)
![S16 VINT period](https://github.com/jotego/jtcores/assets/92724765/f20277e0-1679-4806-89e3-06f1c1caf5bd)
![S16 vint timing](https://github.com/jotego/jtcores/assets/92724765/fb9db3a6-5e74-4706-8ea0-8cf0063b83ff)
