### ISSUE TITLE
CPS1: Add support for Gamushara Battle! Puchi Monster

### ISSUE THREAD

**Issue by ajgowans** [jotego/jtcores#297]
A new game for the CPS1 has been found and dumped: Gamushara Battle! Puchi Monster (がむしゃらバトルプチモンスターズ)

https://www.youtube.com/watch?v=9FMbCs96Daw

Would it be possible to to create an .mra and add support to MiSTer? 

Note: As of Mame 0.256 it is marked:
New systems marked not working
Gamushara Battle! Puchi Monster (Japan 990519) [nnap]
https://www.mamedev.org/?p=526

**Comment by terminator2k2** [comment]
this does the same as ganbare and boots to ram error

**Comment by jotego** [comment]
I need more information about this one and Ganbare to add them. I'd rather not add it just to get a RAM error message. If I can get my hands on a PCB, I should be able to implement whatever is missing.
