### ISSUE TITLE
ngp: [Baseball Stars]

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#305]
commit 6b490a07

The game halts to a white screen. No sound, no reaction to buttons.

**Comment by jotego** [comment]
The code deviates from MAME at PC=FF27AE (frame 536) where MAME takes the jump and the core doesn't. 

```
PC=FF27A9,
XWA0=0,XBC0=0,XDE0=0,XHL0=0,
XWA1=0,XBC1=0,XDE1=0,XHL1=0,
XWA2=0,XBC2=0,XDE2=0,XHL2=0,
XWA3=8100CF,XBC3=20202000,XDE3=30,XHL3=6260,
XIX=FF2FCB,XIY=FF3C07,XIZ=6480,XSP=6BF0,* FF27A9: 
cp (0x6c20),0x00

PC=FF27AE,
XWA0=0,XBC0=0,XDE0=0,XHL0=0,
XWA1=0,XBC1=0,XDE1=0,XHL1=0,
XWA2=0,XBC2=0,XDE2=0,XHL2=0,
XWA3=8100CF,XBC3=20202000,XDE3=30,
XHL3=6260,XIX=FF2FCB,XIY=FF3C07,XIZ=6480,XSP=6BF0,* FF27AE: 
jr Z,0xff27e2
```
(0x6c20) is 0x2FF in the core

**Comment by florgana** [comment]
The game starts about 2 minutes after showing the white screen.
The game let play but some selection texts and images are not visible. 

![Baseball Stars (JUE)](https://github.com/jotego/jtcores/assets/121422911/286be97b-d65b-4396-badf-19ea4fd00def)
![20230717_141817-Baseball Stars (JUE)  M](https://github.com/jotego/jtcores/assets/121422911/38256a86-4315-4300-b1ed-1bcc7143ac68)
![20230717_141823-Baseball Stars (JUE)  M](https://github.com/jotego/jtcores/assets/121422911/e66380af-2f22-4a6e-a376-2880350d6619)
![20230717_141835-Baseball Stars (JUE)  M](https://github.com/jotego/jtcores/assets/121422911/38d8a6d8-2da5-453e-bcef-491b3dce4c63)

**Comment by jotego** [comment]
The game writes to the flash before showing the title screen. Tha process seems to go fast in simulation, but not on the MiSTer

**Comment by jotego** [comment]
The game itself works correctly. The flash problem is taken to a different issue
