### ISSUE TITLE
ngp: [NeoGeo Cup '98]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#306]
No sound. 
The game shows 3 images blinking and then halts to white screen, no reaction to buttons

**Comment by jotego** [comment]
commit b8dff835
sound works
the game hangs up after the first three images in the intro scene

**Comment by jotego** [comment]
commit 78e5acc9
the game does not hang up any more
video still too fast
colors seem inverted sometimes

**Comment by jotego** [comment]
commit: 7cc0b90f
- sound ok
- speed seems ok
- general color problem
- missing bottom score row. The bottom goal is permanently shown
![20230715_222729-NeoGeo Cup '98 (JUE)  M !](https://github.com/jotego/jtcores/assets/1863036/d67b893b-b120-498d-bb3d-03797cd595fb)

**Comment by jotego** [comment]
fixed after adding micro DMA support
