### ISSUE TITLE
ngp: [Puzzle Tsunage Pon]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#307]
No sound.
Right vertical border.
Dark colours. Some images do not have an appropriate color tone. 
Speed of the game very fast. When displaying the images and to play.

![20230712_123414-Puzzle Tsunagete Pon (J)  M](https://github.com/jotego/jtcores/assets/121422911/6f9cd11a-c052-448b-9ae7-ef92cc3a8e29)

![20230712_125958-Puzzle Tsunagete Pon (J)  M](https://github.com/jotego/jtcores/assets/121422911/3d3d9d96-e4e3-403e-a6b8-d55c9f84930c)

**Comment by florgana** [comment]
Commit 01b227ab
It does not start. The game halts to a white screen.

**Comment by jotego** [comment]
After a long white, likely due to flash write attempts, the core starts correctly.
