### ISSUE TITLE
ngp: [King of fighters R-1]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#308]
No sound.
Missing initial images. Game starts with flashing white screen, then written game name and stay black screen with no prompts, react with 1 (ctrl) button and show splash screen.
The select **Start,** shows another selection screen that reaction only to some number buttons, hanging the game or restarting it. After of it hangs or sometimes after reset it shows a striped screen.

![20230712_141338-King of Fighters R-1 (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/767bccb5-9712-4d3f-893a-654f0f7f20d3)

**Comment by jotego** [comment]
commit: b8dff835
the intro sequence run for a few seconds, with music upto this screen:

![20230715_171406-King of Fighters R-1 (JUE)  M !](https://github.com/jotego/jtcores/assets/1863036/bf5066cb-7bff-46ce-a3b4-55d89c4e26b8)

**Comment by jotego** [comment]
commit 42b66755 The game works and seems stable. 

When choosing a character, the image becomes corrupted
![20230716_124146-screen](https://github.com/jotego/jtcores/assets/1863036/f7ec56cd-9837-4aa4-a01e-8e1c8c4a1699)

**Comment by jotego** [comment]
commit 80f26c27
fixed character selection. The game hangs up at the beginning of a battle

**Comment by jotego** [comment]
commit 39fe6345
The game does hang up at the beginning f a battle. It hangs up at the end now.

**Comment by florgana** [comment]
It happens like in the baseball game, after a battle it stays in white screen for a short time and then shows the option to continue the game

**Comment by jotego** [comment]
Commit: 7cc0b90f
Seems playable
