### ISSUE TITLE
ngp: [Melon Chan's Growth Diary]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#309]
No sound.
Doesn't display boot images correctly. The colors are wrong, it looks dark. Does not show white borders as video format in images. (img 1 & img 2)
The selection to "start" the game are not seen. (img 3)
When you start the game it lets you do some movements but after a short time it crashes and doesn't react to the buttons (img 4)

(img 1)
![20230712_150945-Melon Chan's Growth Diary (J)  M](https://github.com/jotego/jtcores/assets/121422911/fa1bfcdc-3edd-451a-911f-6eee286fe985)
(img 2)
![20230712_150958-Melon Chan's Growth Diary (J)  M](https://github.com/jotego/jtcores/assets/121422911/e100af61-d855-4bd3-8cee-d8507e3adcc9)
(img 3)
![20230712_153340-Melon Chan's Growth Diary (J)  M](https://github.com/jotego/jtcores/assets/121422911/6d9f49ff-5454-4830-8b39-b0c04c24c48d)
(img 4)
![NODATE-Melon Chan's Growth Diary (J)  M _0002](https://github.com/jotego/jtcores/assets/121422911/792ad517-7f56-4374-9229-53accf681241)

**Comment by jotego** [comment]
commit: b8dff835
there is sound but the graphics look corrupted in the room now and the game hangs up soon after entering the room

![20230715_172240-Melon Chan's Growth Diary (J)  M](https://github.com/jotego/jtcores/assets/1863036/8062c426-f1a8-4be8-8293-b4a58c4ce133)

**Comment by jotego** [comment]
colors are ok in 132b7d0aa but it is still not playable.
