### ISSUE TITLE
ngp: [Neo Cherry Master]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#310]
No sound.
Wrong layer colors. 
The right vertical bar does not allow a full view of the screen
You win in the first round with any combination, sometimes it lets you continue playing until in any round the credit only goes up to 9999 and it hangs, other times the credit doesn't stop moving and the amount restarts when it reaches the limit. In both options it does not react to the buttons.

![20230711_165726-Neo Cherry Master (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/dd5e7356-4274-4de7-82d8-b01c5982a018)

![20230712_163139-Neo Cherry Master (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/f9fa2c14-873f-4257-a6dc-21350bfd73c1)

![20230712_163720-Neo Cherry Master (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/03040fe6-9a51-4c7b-9ef1-30296c45f1a6)

![20230712_163957-Neo Cherry Master (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/a6739513-26cd-47d8-82ff-02540ca6b961)

**Comment by jotego** [comment]
The carry in the DAA instruction was wrong.
