### ISSUE TITLE
ngp: [Pocket Tennis]

### ISSUE THREAD

**Issue by florgana** [jotego/jtcores#311]
No sound.
Right vertical bar on startup images. 
Shows several images and then hangs with a gray screen and sometime blinks trying to display something, no reaction to buttons.

![20230712_173519-Pocket Tennis (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/82d5909a-7570-417d-a5b6-ebfdd36b20fa)

![20230711_170828-Pocket Tennis (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/6a852ecb-bf6b-4089-8e2f-eb7c56c5b0bb)

![20230711_170906-Pocket Tennis (JUE)  M !](https://github.com/jotego/jtcores/assets/121422911/d9ef8a14-c7ae-4f48-abb8-11db4a24ad52)

**Comment by jotego** [comment]
commit: 7cc0b90f
Seems playable
