### ISSUE TITLE
6306 PROM addition to the Arcade KiCAD library request.

### ISSUE THREAD

**Issue by antongale** [jotego/jtcores#314]
Is there any chance you can add the attached 6306 512x4 bit PROM to the arcade KiCAD library?

[6306.zip](https://github.com/jotego/jtcores/files/12209214/6306.zip)

Thank you!

**Comment by jotego** [comment]
Of course, @antongale 
@etriana85 please check whether the part is missing. If so, add it.

**Comment by jotego** [comment]
Thank you

**Comment by etriana85** [comment]
Correction of 6306
![6306](https://github.com/jotego/jtcores/assets/92724765/4712adfd-1d26-4fea-889f-eb461c6069ae)

**Comment by etriana85** [comment]
This device is already available in the Arcade library, under the name of 53/63xx-1
