### ISSUE TITLE
x-men: medidas de objetos

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#318]
Objetivo:

- Entender cómo el juego y el chip de objetos usa la RAM durante los ciclos de DMA (cuando OBJ/IRQ está alto)
- ¿Varían A13~A12 según la escena o el _frame_?
- ¿A qué ritmo se lee la memoria durante DMA?

Procedimiento:

- Durante DMA (OBJ/IRQ alto) mide las señales A13~1. Si no puedes medirlas todas a la vez, prescinde de señales en mitad del bus (por ejemplo A7, A8...)
- Mide el ritmo al que A1~A3 cambia
- Deja pasar distintas partes de la demo del juego y mira si A13~A12 cambian durante DMA o si siempre tienen un valor fijo

![imagen](https://github.com/jotego/jtcores/assets/1863036/0e91eb64-1ff4-4824-a276-62e263a86754)

**Comment by jotego** [comment]
El orden del bus A del chip no tiene por qué coincidir con el de la CPU necesariamente. Tienen que estar ordenada de forma que durante el DMA el bus haga una cuenta ascendente. A0 tiene que ser la que conmute más rápido, luego A1, etc. 

![imagen](https://github.com/jotego/jtcores/assets/1863036/86a3c344-c961-4129-bff2-24d427679679)

Tiene que ser algo parecido a esto:

![imagen](https://github.com/jotego/jtcores/assets/1863036/4ec377f5-aa01-44cb-8685-dbac9005e8de)

Prueba a reordenarlas y compara ese orden con _The Simpsons_

**Comment by etriana85** [comment]
Las señales A13~12 varían si DMA esta bajo. Cuando DMA está alto, A13~12 se quedan abajo.
 
![DMA1](https://github.com/jotego/jtcores/assets/92724765/f974fbfb-9d2b-4017-a6ab-ca6e41b0b79c)
![A3~1](https://github.com/jotego/jtcores/assets/92724765/a4e8ad82-c9f5-48da-b8da-c7afd1f3ba02)
![vsyn vs mda](https://github.com/jotego/jtcores/assets/92724765/15129010-5a7d-471b-8ee1-cd2b121a9da4)
