### ISSUE TITLE
The Fairy Land schematics

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#319]
Extract schematics for _The Fairy Land_ PCB

**Comment by etriana85** [comment]
Work in progress

**Comment by jotego** [comment]
@etriana85 acciones después de revisar la placa adaptadora:
- [ ] Revisar la placa adaptadora para entender por qué algunas huellas no tenían el tamaño correcto
- [ ] Corregir las huellas en la placa
- [ ] Reducir el largo del conector JAMMA macho para que no sobresalga tanto al encajarlo
- [ ] Quitar 1mm por cada lado al ancho del conector JAMMA macho para que encaje mejor

**Comment by etriana85** [comment]
Quitar 1mm por cada lado al ancho del conector JAMMA macho para que encaje mejor: Creo que el problema no es del largo sino del ancho. 
Trabajaré hoy en la reducción del pad de JAMMA. Actualmente tiene 10mm. Te parece bien dejarlo en 7mm?
