### ISSUE TITLE
the simpsons: schematics for object chips

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#320]
Hoy o mañana llegará una placa de The Simpsons, préstamo del museo Arcade Vintage. Los esquemáticos de Konami carecen de la parte de los objetos. Debería ser muy similar a X-Men. Extrae el esquemático para esa sección.

**Comment by etriana85** [comment]
Work in progress.

**Comment by etriana85** [comment]
Adjunto esquemático de la extracción de objectos, fondo y colmix.
[The simpsons.pdf](https://github.com/jotego/jtcores/files/12292364/The.simpsons.pdf)

**Comment by etriana85** [comment]
Adjunto medidas solicitadas:
![~VBLK  VS ~ DMA](https://github.com/jotego/jtcores/assets/92724765/c9d6bcd7-26b9-44bd-b1c1-d0368fe7aa38)
![~VBLK](https://github.com/jotego/jtcores/assets/92724765/173135b5-1efb-4d55-b30c-4b07c35402e9)
![~VSYNC](https://github.com/jotego/jtcores/assets/92724765/4c417d1a-473a-4c2c-8238-1787e6d08c15)
![~SYNC](https://github.com/jotego/jtcores/assets/92724765/75b43e24-b6ae-4f08-9ffd-3d9ef6537878)
![~CSYNC](https://github.com/jotego/jtcores/assets/92724765/f01ecff0-e5b5-4d12-ac97-cf0d28a97c7a)
[SIMPSONS.webm](https://github.com/jotego/jtcores/assets/92724765/f8169ed2-3167-42e0-8193-8f0fd0151616)
![ancho DMA simson](https://github.com/jotego/jtcores/assets/92724765/81a75ddf-3ed3-4bcb-afaa-00edeff56a63)
![simpsons DMA width](https://github.com/jotego/jtcores/assets/92724765/2b5f1601-6888-4e07-a9a7-5dcb68caf7bd)
