### ISSUE TITLE
punkshot: dump 053736

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#336]
Make adapter to read the chip output as a memory and dump it

**Comment by etriana85** [comment]
![053736](https://github.com/jotego/jtcores/assets/92724765/b23f299a-0c34-4e97-a441-3ed593300f14)
![053736-1](https://github.com/jotego/jtcores/assets/92724765/619ba044-ae6e-4283-b99d-7817cf805a7b)
![053736-2](https://github.com/jotego/jtcores/assets/92724765/1f460e82-014e-4cf5-b014-ee9057ffa218)

**Comment by jotego** [comment]
Caius has just published his own version [here](https://wiki.pldarchive.co.uk/index.php?title=Punk_Shot)
