### ISSUE TITLE
The Final Round schematics

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#341]
- [x] Change A[0..12] to A[1..12]

![imagen](https://github.com/jotego/jtcores/assets/1863036/c55f0301-fa7b-4ccb-a700-76be28a41f97)

- [x] Add number to A bus in symbol. Keep the same order as in the D bus

![imagen](https://github.com/jotego/jtcores/assets/1863036/2bbaade2-2eba-4b5a-8859-27e2413c2282)

- [x] Align U176 and U177 vertically to make the signal path more obvious for all 8 bits of U5

![imagen](https://github.com/jotego/jtcores/assets/1863036/0943384d-ebe3-402a-9701-a17e51c09c5a)

- [x] Delete buffer drawing in MX23C4100 symbol because it is confusing. It does not match the function nor the pin names of the device

![imagen](https://github.com/jotego/jtcores/assets/1863036/7cee8a99-4472-446f-8a15-2e8dcb3a19bc)

- [x] Align the text columns (happens in several places)

![imagen](https://github.com/jotego/jtcores/assets/1863036/86600b9e-4cc1-48d4-9cc4-8af83e8db34d)

**Comment by etriana85** [comment]
Done!
![issue#341-1](https://github.com/jotego/jtcores/assets/92724765/ba0ef94f-eaba-4013-84af-4f165cfc04fd)
![issue#341-2](https://github.com/jotego/jtcores/assets/92724765/31f2c5d4-6479-4ce4-99d5-f1174a1fed4d)
![issue#341-3](https://github.com/jotego/jtcores/assets/92724765/b35c639b-2524-4e6e-ba7f-eadd8f7319f0)
![issue#341-4](https://github.com/jotego/jtcores/assets/92724765/cd6a2516-30eb-46b0-9789-931ab9cd2e87)
![issue#341-5](https://github.com/jotego/jtcores/assets/92724765/41134486-4203-4ff1-a3e6-c4b080f0a2a0)

**Comment by etriana85** [comment]
![issue#341-5](https://github.com/jotego/jtcores/assets/92724765/4a14db70-7004-4f43-81d1-03c3503cc00a)

**Comment by jotego** [comment]
Another one:

- [ ] change to De Morgan (sprites sheet)

![imagen](https://github.com/jotego/jtcores/assets/1863036/af4124e4-c3ea-4f1e-aa43-9d5374707ce4)

**Comment by etriana85** [comment]
Done!
![issue#341-6](https://github.com/jotego/jtcores/assets/92724765/1616c3ce-e624-4b1f-be83-dcf7519a31d2)
![issue#341-7](https://github.com/jotego/jtcores/assets/92724765/3c0e7be1-d32c-455e-a4f1-9d88fbfab92e)
