### ISSUE TITLE
fround: measure sprite memory

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#344]
On the Final Round PCB, measure signals OA12-OA4, /URW, /LRW, /OE and DMA shown on sheet _Sprites1_. We are trying to understand whether there are memory writes during DMA.

Measure it while the game is showing a combat, so there are plenty of sprites on screen.

![imagen](https://github.com/jotego/jtcores/assets/1863036/cbb8a2b2-e536-4c99-8842-ec2a2582a663)

**Comment by etriana85** [comment]
![DMA](https://github.com/jotego/jtcores/assets/92724765/416b856c-b01f-41ba-9caa-0fbe72586fc4)
![~LRW  ~URW TFR](https://github.com/jotego/jtcores/assets/92724765/9f11508f-dc8b-46d3-8606-7df40f01a9ad)
![OA4 TFR](https://github.com/jotego/jtcores/assets/92724765/3ee84b5b-4f26-42d1-8623-a53d5d9bb80b)
![~OOE TFR](https://github.com/jotego/jtcores/assets/92724765/1cfdf1fc-8495-433c-9833-e11414a35fc7)
