### ISSUE TITLE
Road Fighter  the car not start smoothly

### ISSUE THREAD

**Issue by Ronalvel** [jotego/jtcores#346]
In the Mister when the car starts it is lost like a frame in the Miste, it does not start smoothly, I have the original pcb that problem does not occur, in the Mame it also works smoothly.

**Comment by jotego** [comment]
Start accelerating with the low gear. This core is for a rather simple PCB for which we had schematics and the PCB itself so I am bit skeptic about some oddity like the one you are describing. Please make sure your setup in MiSTer is correct, that you are executing the same actions and that your DIP settings and game version is the same. Running the PCB on a CRT may also blur some graphic elements that will be noticeable on MiSTer's HDMI output.
