### ISSUE TITLE
Splatter House: measure video signals

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#348]
Medir en Splatter House las señales VSYNC, HSYNC, VBLANK, HBLANK para que esté clara su duración, polaridad y posición relativa.

Medir la frecuencia del reloj, que debería ser 49.152MHz pero puede haberse corrido con el tiempo

![imagen](https://github.com/jotego/jtcores/assets/1863036/6d17d3e1-f8cf-40d9-bfca-f96ad2b83c4a)

Son los mismos esquemáticos que PacMania

**Comment by etriana85** [comment]
![~HB - ~HS SHOUSE](https://github.com/jotego/jtcores/assets/92724765/8dc7dd56-011a-4d28-bdd9-a62f43e4c3bc)
![~HB SHOUSE](https://github.com/jotego/jtcores/assets/92724765/cc63af59-5ead-45e4-9b1c-ecdfcc24c682)
![~HS SHOUSE](https://github.com/jotego/jtcores/assets/92724765/13ee6a1a-a19a-4dcf-916d-4af4247f36f8)

**Comment by etriana85** [comment]
~VBLANK Lo veo siempre bajo (CERO) y ~VSYNC alto  (UNO).
EL RELOJ: 46.5 MHz ~ 50 MHz. Pero esta en el pin 33.

**Comment by jotego** [comment]
No hay bastante información en las gráficas para reproducir las señales HB/HS. Es imposible saber el periodo de las señales con esas gráficas o la longitud de la parte baja de HS y HB

Es necesario medir el reloj con una precisión de al menos 1%

VB/VS tienen que funcionar o no habría imagen en el monitor

**Comment by etriana85** [comment]
![HBLANK](https://github.com/jotego/jtcores/assets/92724765/14a80b0f-c0a9-4ad4-a3f9-9cf59b60dac4)
![HSYNC](https://github.com/jotego/jtcores/assets/92724765/958226ab-0c42-422f-bf97-7ed2447fe92f)
![VBLANK](https://github.com/jotego/jtcores/assets/92724765/985c2227-a5c3-4017-a37d-3eaad0efafd9)
![VSYNC](https://github.com/jotego/jtcores/assets/92724765/cd2e165e-99ff-4a87-b3e4-37555f63c287)

**Comment by etriana85** [comment]
![HBLANK](https://github.com/jotego/jtcores/assets/92724765/6ac47b32-5abf-4189-a005-f02203c4684c)
![HSYNC](https://github.com/jotego/jtcores/assets/92724765/05fa2128-3dfb-46bf-b650-14bda6f12737)
![VBLANK](https://github.com/jotego/jtcores/assets/92724765/a326c591-9c17-431c-8a7f-dd0e32a7a9b6)
![VSYNC](https://github.com/jotego/jtcores/assets/92724765/09ab195c-eb21-4498-926e-8623a0c42e3f)

**Comment by etriana85** [comment]
![1HSYNC](https://github.com/jotego/jtcores/assets/92724765/21ad26b0-5833-4cb0-9537-0f4aeaea8570)
![2VSYNC](https://github.com/jotego/jtcores/assets/92724765/50e94fa1-ee81-4c02-807b-874151f75b9f)
![3VBLANK](https://github.com/jotego/jtcores/assets/92724765/af39f817-cad0-4d83-bf6a-08602592e1a5)
![4HBLANK](https://github.com/jotego/jtcores/assets/92724765/0fed5c21-3691-48dc-a795-280c48aa465d)

**Comment by etriana85** [comment]
El reloj: 49,1 MHz 48.8 MHz

He corregido las señales, las he tomado de un chip personalizado (CUS133 - pág. 11).  Y en cuanto el reloj, lo había seguido erroneamente y estaba midiendo el pin equivocado.

Quedo atenta a cualquier novedad.

**Comment by etriana85** [comment]
![CUS133](https://github.com/jotego/jtcores/assets/92724765/97c2f415-9328-44e0-8121-0bae8763a567)

**Comment by etriana85** [comment]
![~VSYNC_FS](https://github.com/jotego/jtcores/assets/92724765/35ca1800-80e6-4f95-9f70-0aa7feaec8a1)
![~VSYNC_P0](https://github.com/jotego/jtcores/assets/92724765/b32268d0-f4ae-40ff-a122-5944a0efbfe0)
![~VSYNC_P1](https://github.com/jotego/jtcores/assets/92724765/7a84ca41-94b2-426e-a0db-3de9ed956efd)
![~VSYNC_PR](https://github.com/jotego/jtcores/assets/92724765/e329ca1f-021e-4074-b41f-005f1a5d936e)

**Comment by etriana85** [comment]
![~VB_FS](https://github.com/jotego/jtcores/assets/92724765/ce6c7576-adf8-44b9-8a0a-129333a7681a)
![~VB_P0](https://github.com/jotego/jtcores/assets/92724765/df00f843-d6f6-42ee-b9e2-f3198df57f58)
![~VB_P1](https://github.com/jotego/jtcores/assets/92724765/6fd92084-314e-427b-8e0b-fd915a75408c)
![~VB_PR](https://github.com/jotego/jtcores/assets/92724765/5b504a93-a739-45d3-8207-64a1abbcb106)

**Comment by etriana85** [comment]
![~HS_FS](https://github.com/jotego/jtcores/assets/92724765/3178167d-6245-4dc5-9a4d-2915ee876117)
![~HS_P0](https://github.com/jotego/jtcores/assets/92724765/9e1b5ca1-adf0-43ba-89d9-590dd2182ce8)
![~HS_P1](https://github.com/jotego/jtcores/assets/92724765/98ee127d-89e2-45fb-8bbe-3fe63547a0da)
![~HS_PR](https://github.com/jotego/jtcores/assets/92724765/dcd496e9-4384-4e62-b49b-7b122490195e)

**Comment by etriana85** [comment]
![~HB_FS](https://github.com/jotego/jtcores/assets/92724765/53244bd2-dad6-4c06-a012-0948e5971e30)
![~HB_P0](https://github.com/jotego/jtcores/assets/92724765/d19f3dd8-8571-4b56-a844-dc8c6a1fddf1)
![~HB_P1](https://github.com/jotego/jtcores/assets/92724765/d5f2a0bb-7b5a-4fc7-a4ec-2e9c6222d117)
![HB_PR](https://github.com/jotego/jtcores/assets/92724765/837cda29-cb33-4f18-b7c0-2f0ba614f15e)

**Comment by etriana85** [comment]
- pulsos para medir H de CLK12,2MHz
- HS activo 64 pulsos
- HB activo 192 pulsos
- Periodo HS/HB 768 pulsos
- Retraso de activación HB a activación HS 64 pulsos

- pulsos para medir V de HS
- VS activo 8 pulsos
- VB activo 40 pulsos
- Periodo VS/VB  264 pulsos
- Retraso de activación VB a activación VS 8 pulsos

**Comment by etriana85** [comment]
![~VB_FS](https://github.com/jotego/jtcores/assets/92724765/872cd534-37d6-4cc0-bdf6-23b5818bd934)
![~VB_P0](https://github.com/jotego/jtcores/assets/92724765/0fea039f-b261-4e7c-b108-a5c35d4cd132)
![~VB_P1](https://github.com/jotego/jtcores/assets/92724765/2e7b75d4-1c80-4f3b-af7b-025803801e4e)
![~VB_PR](https://github.com/jotego/jtcores/assets/92724765/acdc398f-cfec-4645-83c5-fe026e1df7a9)

**Comment by jotego** [comment]
Todo correcto. Gracias
