### ISSUE TITLE
pang: update Pocket cores with NVRAM support

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#352]
El *target* de JTFRAME para Pocket target ahora soporta memorias no volatiles (NVRAM/EEPROM). Hay que actualizar los siguientes cores

- [x] CPS1 (only Pang! 3 uses NVRAM)
- [x] Pang
- [x] roadf
- [x] track

Para cada core:

- regenerar los ficheros JSON de la pocket: `jtframe mra core-name`
- recompilar `jtcore core-name -pocket --nodbg`
- probar en la Pocket `jtbin2sd`
- Los cambios en las opciones a través del menú OSD o de la pantalla de servicio (F2 en la SiDi, pero en la Pocket se entra pulsando uno de los botones pequeños al lado del botón Analogue y uno de los grandes -dos en concreto). Al salir del core, los cambios deberían guardarse y al volver a cargar el core las opciones deberían recordar los valores
- Si todos los cores van bien, recompilar para JTBIN con `jtupdate cps1 pang roadf track -t pocket --git` y empujar al JTBIN local común

**Comment by florgana** [comment]
Commit 0341eb2 
El core **Pang** funciona.
Los cores **Roadf** y **Track** no funcionan, al iniciar muestran solo 0 en pantalla, adjunto screenshots
![20230922_142741](https://github.com/jotego/jtcores/assets/121422911/5fd3c9f9-8607-4ce2-9c17-89e0df2d122d)

**Comment by jotego** [comment]
- CPS1 tested and updated on JTBIN 0f730d54

**Comment by jotego** [comment]
Could not verify the bug report using 1ebf3521 and May-23 firmware for the Pocket. Pushing changes to JTBIN
