### ISSUE TITLE
Namco System1 CUS117 (Memory Mapper)

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#361]
¿Es posible desoldar el CUS117 y ponerle un zócalo?
¿Tenemos dos chips de este tipo? (uno en la placa de Splatter House, otro en PacMania?

Desoldar y poner zócalos:
- [ ] PacMania
- [ ] Splatter House

**Comment by etriana85** [comment]
Según los recursos que tenemos, no es posible poner zócalo, ya que son chips smd. 
[cus117.odt](https://github.com/jotego/jtcores/files/12713827/cus117.odt)
