### ISSUE TITLE
simson: check 2-player versions on the Pocket

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#370]
Some users have reported that the 2-player versions do not work on the Pocket. @florgana, can you check it?

**Comment by florgana** [comment]
Yes, commit 4a121ad5
The 2-player versions do not work on the Pocket.

**Comment by jotego** [comment]
How about on the MiSTer? Does it work correctly there?

**Comment by florgana** [comment]
In MiSTer the sound and images is ok, but you can play only one player. The version 2 players world set 1, sometimes only show the player 2 to choose. 
![Captura de pantalla -2023-09-29 13-48-46](https://github.com/jotego/jtcores/assets/121422911/4a4e388e-1793-46d0-82af-05d8f3b99698)
