### ISSUE TITLE
gng: make mister/pocket release

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#375]
Recompilar y lanzar gng sólo para Pocket y MiSTer

```
cd $JTBIN
git pull
cdjt
jtupdate gng -t mister,pocket --git
cd $JTBIN
jtbin2sd --git
jtbin2mr --git
```

Comprobar:

- [x] Pocket
- [x] MiSTer
- [x] Los ficheros modificados en JTBIN tendrían que ser sólo los de GNG, y no otros cores
- [x] Los DIP switches tienen que funcionar bien. Comprobar en el modo de servicio que la configuración que se ve en el OSD es la que ve la máquina

Si todo está correcto:

```
cd $JTBIN
mergenkill
git push
```
Y marcar #349 como "Done" en el apartado de _Projects_

**Comment by florgana** [comment]
Done! All okay.

**Comment by jotego** [comment]
There's no commit in [JTBIN](https://github.com/jotego/jtbin/commits/master). Did you forget to _git push_ it?

**Comment by jotego** [comment]
released in https://github.com/jotego/jtbin/tree/31bc8232de75beb61d6c98beaad0b19aec8e8763
