### ISSUE TITLE
Super Hang-On and OutRun audio crackle.

### ISSUE THREAD

**Issue by Damedade** [jotego/jtcores#379]
I've been experiencing audio crackle with both these cores since the recent update on MiSTer.

Using 128MB and HDMI out

It is more noticeable on Super Hang-On, I advise wearing headphones.

**Comment by jotego** [comment]
- tested on v1.2.72, released on 22nd Sep '23
- I cannot hear any problem using the optical audio output

This might be a generic MiSTer-HDMI sound problem or something related to your setup.

Another possible cause:

I think MiSTer resamples the sound at 48kHz to send it over HDMI. That will create aliasing. So far, nothing is done either on the cores or MiSTer side to prevent aliasing. I want to tackle the possible aliasing in a generic way for all cores in #402. That could be the fix to your problem, assuming that was the cause.

No specific actions for these two cores at the moment, sorry.
