### ISSUE TITLE
shanon/outrun: pocket analog controls are too sensitive

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#384]
Some users report a drift when using the dock. It could be due to the Pocket being too sensitive.

**Comment by Dawbo66** [comment]
using a Bluetooth controller paired to the dock causes the bike to steer to the left constantly, using a analogue controller works as intended.

**Comment by jotego** [comment]
Tested fe34995 with a wired 8BitDo SN30 pro. When the device is not docked, the Super Hang-On works as expected. As soon as you dock it, the accelarator (button A) stops working, although it seems to have some sort of effect as the speed toggles in a different way. Analog controls are ignored and the motor bike just goes left.
