### ISSUE TITLE
.gitignore *.qsf *.qpf *.f  for new targets

### ISSUE THREAD

**Issue by somhi** [jotego/jtcores#403]
global .gitignore includes  *.qsf *.qpf *.f
when adding new targets  *.qsf *.qpf *.f  does not get added to remote

my solution is to remove those filters from global .gitignore
I included a .gitignore inside cores/ just for *.qsf *.qpf

**Comment by jotego** [comment]
That sounds perfect. I've changed too in commit 0303dd7b

**Comment by somhi** [comment]
Great.  I've just realized that same should appy to *.hex files   
I have two hex files in my targets as well
