### ISSUE TITLE
SF: corrupted object data

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#406]
**Street Fighter**
From the start of the game, all characters are **shown in double** and the **movement is poor**
Commit: [ff5cde2](https://github.com/jotego/jtcores/commit/ff5cde289d7fc29d0d12f43fcea09495635ffe3b)
![screen image Street Fighter](https://github.com/jotego/jtcores/assets/110815304/35d80e6b-0fdf-405d-9a88-86a104170644)

**Comment by jotego** [comment]
Occurs in MiST too b466bc8c

**Comment by jotego** [comment]
Green: works
red: fails
regression introduced in da37a0249264452852a3c6dd4b39cb117d7b2d53
![image](https://github.com/jotego/jtcores/assets/1863036/a52806ff-c576-478d-aaa5-55fef402cdbb)
