### ISSUE TITLE
shouse: MCU lock up

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#410]
The MCU, sound CPU and other CPUs in Namco System 1 communicate through the _TRIRAM_. MAME uses a hack to get the system to boot by locking writes from the MCU to _TRIRAM_'s address zero after the value $A6 has been written (see namcos1_m.cpp line 584). This does not match the schematics as the MCU is always allowed to write anywhere. On the FPGA core, it is also required to boot up, but it shouldn't.

The MCU writes A6 to C000 once, then it will _copy_ there whatever it reads from C02F. The MCU code only access C02F explicitly twice:

1. When reading it to transfer it later to C000. But the code can never produce the $A6 value again as only the lower nibble is parsed.

![image](https://github.com/jotego/jtcores/assets/1863036/c3c8ed52-5a27-43a3-a121-bd85e2d46b4c)

2. It clears it at this subroutine. MAME debugger never reaches this point.

![image](https://github.com/jotego/jtcores/assets/1863036/fd602665-1013-456b-a48a-0be565bb4ae4)

- The sound CPU ROM does not refer to any 702F address
- The code for the two _main_ CPUs contains `B7 30 2F` a few times, `STA $302F`, these get mapped to the _TRIRAM_. It can be seen writting a 0E and then 08 during the first 150 frames.

Measurements
- SUBRES is not related to VB
- CIRQ occurs at entering VB and lasts for ~31.2us
- The PCB has a first SUBRES clear period of ~1s and then there is a short SUBRES assertion
- The minimum length for SUBRES seen in the PCB would not require a counter to enforce it in the mapper. It seems to agree with simulation as it is

Things to look at:

- The MCU writes to the EEROM chip and then waits until it reads the same value from it. This process must have taken a few checks on a real EEROM, slowing down the MCU
- The mapper model may be wrong, particularly about the reset signal to the sub, MCU and sound CPUs
- Should the sub reset signal have a minimum length?

**Comment by jotego** [comment]
**Introducing a delay after each MCU write to EEROM**

- Forcing a delay after EEROM writings equivalent to 5 check-loop iterations in the MCU do not solve the lock-up issue
![image](https://github.com/jotego/jtcores/assets/1863036/41602c28-881b-4db2-a7b8-520760f03435)


-

**Comment by jotego** [comment]
The reset signal and LVBL are not related in the PCB. But, the PCB does lock up during boot up occasionally.

The core around commit 82ccf09ca0ca798f3048c502918a8c0b9b923a36 may fail to boot up in simulation when bypassing the ROM load. Comparing waveforms shows that the timing of the VB-related IRQ is important. Linking the SUBRES to the VB edge fixes the problem in simulation. Still, the sound and MCU are messed up during game play.

**PCB measurements of LVBL and global RESET**
Most consistent relationship after a while with no power:
![DS1Z_QuickPrint3](https://github.com/jotego/jtcores/assets/1863036/52914eb2-7980-4b87-805b-f96e44490c4b)

Driving down the supply not to zero and then back up again shows other relationships
![DS1Z_QuickPrint4](https://github.com/jotego/jtcores/assets/1863036/3e997551-ad09-4922-9f79-6df2c67630d5)
![DS1Z_QuickPrint5](https://github.com/jotego/jtcores/assets/1863036/12670c1e-e728-4e55-9f2b-91a615b0feb6)

**Comment by gyurco** [comment]
The $a6 hack breaks Shadowland. The game does a RAM check, and as it reads back $a6 from $1000 (in the CPU's POV) instead of the value it written before, it fails. But even removing the hack, this game doesn't want to work, it stops later on (the memtest passes at least).

**Comment by gyurco** [comment]
This one works with all games so far:
https://github.com/jotego/jtcores/commit/eea4c381234b824a7e2b0a7b42bed0ee02eacab2

**Comment by jotego** [comment]
Very interesting to see it working well with a different approach. It still does not make sense that all this is needed from looking at the schematics, but I guess we'll have to live with the hack. 
My PCB does not want to boot anymore and debugging a PCB can be more work than designing a core so I may not be able to research further into this odd lock up.
