### ISSUE TITLE
simson (pocket): save file not created correctly

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtcores#416]
If there are save files present 12C fails on the ROM check at start up in the alternate versions of The Simpsons, the main version doesn't have a problem because it seems to not have a ROM check. Deleting the save files allows them to work until you boot it again.

**Comment by jotego** [comment]
That was a very good hint about the problem. Thank you. Let me check it.

**Comment by jotego** [comment]
The Pocket version seems to dump incorrectly the game EEPROM. MiSTer does it correctly (tested v1.3.1 on MiSTer)

**Comment by jotego** [comment]
Fixed with #327
