### ISSUE TITLE
TMNT: TMNT Metallic noise in some early scenes

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#425]
TMNT
Metallic noise in some early scenes:
- **When the letters appear announcing the second stage**
- **During character selection scene**
[Player_Selection_MISTER TMNT.zip](https://github.com/jotego/jtcores/files/13306420/Player_Selection_MISTER.TMNT.zip)
[Player_Selection_MAME TMNT.zip](https://github.com/jotego/jtcores/files/13306424/Player_Selection_MAME.TMNT.zip)

Commit: fd8f15e

**Comment by jotego** [comment]
There is a bit of clipping on some sounds. There is no clipping during the second stage title screen, but the sound is awkward

**Comment by jotego** [comment]
The sound at the second stage noise occurs while the player's energy is charged up. Using https://github.com/jotego/jt51/commit/898faf289488acf5a7d12df9062a814966b75158 works fine:
[898faf2.mp3.zip](https://github.com/jotego/jtcores/files/13327509/898faf2.mp3.zip)

But version https://github.com/jotego/jt51/commit/a9907cd46ebd6a4830d2ae1bd9600f87d5396f92 breaks it:

[a9907cd.mp3.zip](https://github.com/jotego/jtcores/files/13327521/a9907cd.mp3.zip)
