### ISSUE TITLE
Haunted Castle : Music inconsistent with arcade

### ISSUE THREAD

**Issue by Zekkele** [jotego/jtcores#426]
Music does not sound correct when compared to Arcade pcb.

**Comment by jotego** [comment]
Thanks for reporting it. Can you be a bit more specific about what feels different?

**Comment by Zekkele** [comment]
Sound channel balance seems off. I think its that the Mid range instruments are way too loud?

**Comment by jotego** [comment]
Confirmed in f8166fbb. The problem is in the SCC module. Bug introduced in 3363231b0b0f283e8165027ab4ebb9c7e2565ac9. Fixed in 6c07bb6e.
I will update the files next Friday. Thanks for reporting this.
