### ISSUE TITLE
Pocket: S16B Time Scanner rotated and missing settings

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtcores#436]
In the S16B core, Time Scanner (set 2, System 16B) starts rotated, and no settings come up on the Core Settings menu, only Controls.

**Comment by jotego** [comment]
Cutting down the number of options in the _interact_ file after `"id": 8` (leaving the _Default_ one), fixes the problem. It looks like there are too many options and the Pocket just won't show any (great design as usual when it comes to the JSON files...). 

- Check how many after `"id": 8` can be added
