### ISSUE TITLE
core audit mister ec5b067

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#440]
Core | romset | issue |
----|---|-----------|
karnov | chelnov | blank screen |
kiwi | arkanoid2 | after inserting coins, COIN OVERFLOW is displayed and the screen freezes |
bubl | bublbobl | as soon as STAGE 1 starts, the screen goes black |
comsc | combatsc | all operations slow |
contra | contra | all operations slow |
do | ddragon | bass noise from the opening |
kiwi | drtoppel | sound effects are low in pitch | 
s16b | dunkshot | scoreboard and game over display screens are odd at 90 degrees sideways. 1P players do not run |
s16 | fantzone | play speed and enemy attack speed are slow |
s16b | fantzn2x | play speed and enemy attack speed are slow |
cps1 | forgottn | can insert coins, but screen display is strange. attached below |
![forgotten world](https://github.com/jotego/jtcores/assets/110815304/2bd43bec-3bf0-4d5c-9817-3ce4155157e6)
s16b | goldnaxe | can see only TEST PROGRAM screen. attached below |
![golden axe](https://github.com/jotego/jtcores/assets/110815304/75ab418a-7979-4c7d-9cd0-de9c3bda0e19)
cps1 | gulunpa | high-pitched noise continues |
ninja | hbarrel | cross control keys not working |
roadf | hyperspt | control keys not working |
karnov | karnov | blank screen |
kicker | kicker | horizontal screen appears for a moment then blank screen. only sound effects are audible |
pinpon | pingpong | blank screen only sound effects are audible |
tmnt | mia | credits appear in horizontal screen |
s16 | mjleague | cross control keys not working |
mikie | mikie | blank screen only sound effects are audible |
cps1 | pokonyan | can see only TEST MENU screen |
cps2 | pzloop2 |  cross control keys not working |
sbaskt | sbaskt |  blank screen only sound effects are audible |
s16b | suprleag | cross control keys and buttons not working |
cps1 | kod | can see only TEST MENU screen |
aliens | thunderx | blank screen |
track | track |  blank screen only sound effects are audible |
karnov | wndrplnt | blank screen |
yiear | yiear | blank screen only sound effects are audible |

**Comment by jtmiki** [comment]
Still these problems.

Core | romset | issue |
----|---|-----------|
karnov | chelnov | blank screen |
kiwi | arkanoid2 | after inserting coins, SECURITY ERROR is displayed and the screen freezes |
comsc | combatsc | freeze with red screen. Only beeping sound. |
contra | contra | freeze with strange coloured screen. |
do | ddragon | bass noise from the opening. Time counts slow. |
kiwi | drtoppel | sound effects are low in pitch | 
s16b | dunkshot | 1P players do not run |
s16 | fantzone | play speed and enemy attack speed are slow |
s16b | fantzn2x | play speed and enemy attack speed are slow |
cps1 | forgottn | can insert coins, but screen display is strange |
cps1 | gulunpa | high-pitched noise continues |
ninja | hbarrel | cross control keys not working |
karnov | karnov | blank screen |
kicker | kicker | blank screen. only sound effects are audible. |
pinpon | pingpong | blank screen only sound effects are audible |
tmnt | mia | game runs but can't remove credits |
s16 | mjleague | cross control keys not working |
mikie | mikie | blank screen only sound effects are audible |
cps1 | pokonyan | can see only TEST MENU screen |
cps2 | pzloop2 |  cross control keys not working |
sbaskt | sbaskt |  can play but no sound |
s16b | suprleag | cross control keys and buttons not working |
cps1 | kod | can see only TEST MENU screen |
aliens | thunderx | blank screen |
karnov | wndrplnt | blank screen |
yiear | yiear | blank screen only sound effects are audible |

**Comment by jotego** [comment]
All issues have been addressed
