### ISSUE TITLE
pocket: Dimahoo: The in-game Item Sub-Menu in Dimahoo cannot be triggered

### ISSUE THREAD

**Issue by Wraalf** [jotego/jtcores#443]
In Dimahoo the in-game Item Sub-Menu cannot be triggered due to a conflict with the button combination used to access the test menu.

**Comment by jotego** [comment]
Special buttons set to:

- coin + button 1 = pause  (no change)
- coint + button 2 = test button (changed, will trigger the setup menu)

This will go live in the next update.
