### ISSUE TITLE
PCBs needed for schematic extraction

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#446]
Taito games using the 68705 MCU:

- [ ] 40 Love
- [ ] Birdie King
- [x] Birdie King 2
- [ ] Birdie King 3
- [ ] The Legend of Kage
- [ ] LSA Squad
- [ ] Mat Mania
- [ ] NY Captor
- [x] Pit & Run
- [ ] Return of the Invaders
- [ ] Slap Fight
- [ ] Xain'd Sleena
- [x] [Taito F3](https://www.ebay.es/itm/325904097822?hash=item4be165e21e:g:CAMAAOSw-YdlZH6T&amdata=enc%3AAQAIAAAAwD8K4jbovymAu%2BceIS6RvBB5dIKLMHGmlO0%2FCI58HgJt0B%2Fv3XK5RV1EvSBmAQCCW6lfB%2BjE1gjzYcfUrArGbVlHgkruRgvEJFYiOTk9WM9%2FSG%2BZERUvsnjkQCYj5%2Bc%2FTN%2FIX1n2aqgNdvPCL6sbMTfU4pU0iNkmNdPpJAXK3m92Ioo%2BH7IZdjDggtZcT8wiTPpql%2FtqHLKTAc3VmhtB%2FIZX4mAk0DR552OREkvmXyW7wl%2FDR9gL9uN%2FOpMZmF%2Bs2w%3D%3D%7Ctkp%3ABk9SR87vs9KKYw)

Atari games:
- [x] Marble Madness II

CAPCOM:
- [ ] [Son Son](https://www.ebay.es/itm/154513614627?hash=item23f9baa723:g:rRUAAOSw2mpi~ZfO&amdata=enc%3AAQAIAAAA4BXV6aDR9oelnyTuopYElGfoYrNXWen2k5gJCzzrLRt2tF4xRYPNHJTDLA9qm9S%2FxMUSdSPXCjCMuSJfB5E7%2F%2Fa1%2Fn3x2sKkE4oDFWr2PdmGPmp0woPpMoCJZosDAawDJnJwl5ZbE%2FAU1Yd%2B6pXqYyxKoKwPfnUCAybezn%2FbcHdqUj7rTBjAamjTs1I2AtWPnUiWl%2Fifm7A%2F%2Ffmu0dVuSMqZZcgjGd%2BiAUXHFbn14fskBXuSk7X4jzZKe6e8cvJ4HYZ75WYn5GGBpDbE%2FLDpVBIUt65N7JJAM%2FsA6MPQY%2Ff%2F%7Ctkp%3ABFBMzO-z0opj)
- [ ] Hexion
- [ ] Escape Kids
- [ ] Roller Games
- [ ] Gaia Polis
- [ ] Monster Maulers
- [ ] Mystic Warriors
- [ ] Dragon Ball Z
- [ ] Dragon Ball Z 2
- [ ] Xexex
- [ ] Premier Soccer

**Comment by etriana85** [comment]
He encontrado solo los manuales de:
- The Legend of Kage (TAITO)
- LSA Squad (TAITO)
- Mat Mania (TAITO)
- NY Captor (TAITO)
-  Slap Fight (TAITO) - A.L.C.O.N

- Birdie King 2 (TAITO): Descargué el sch, pero aparecía Birdie King 2, no 1 ni 3

**Comment by jtmiki** [comment]
I bought a NEW Taito F3 mother board and 2 cartridges.
We will get them next week.

**Comment by jtmiki** [comment]
I bought a PCB of Dragon Ball Z and it arrived yesterday.
