### ISSUE TITLE
kiwi: sound effects are wrong

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#449]
The New Zeland Story

A bad sound effect is played when using the fireball baton weapon. 
In the Service Test of the game it can be played with "SOUND 16".
commit: b25223e

**Comment by jotego** [comment]
fixed in 009d746

**Comment by skutis** [comment]
I think the reference https://github.com/jotego/jtcores/commit/009d7461bf035e35dcab0f6d68e01732fbee7769 is wrong here.

**Comment by jotego** [comment]
it is still broken in 415c3d2

**Comment by jotego** [comment]
Reproduce with 

- `jtsim -setname tnzso -dipsw 0xfffa -video 360 -w 300 -inputs -d VERILATOR_KEEP_JT03`
- [sim_inputs.hex.zip](https://github.com/jotego/jtcores/files/14000509/sim_inputs.hex.zip)

**Comment by jotego** [comment]
The CPU is writting this to JT49:

![imagen](https://github.com/jotego/jtcores/assets/1863036/2a834714-fe4d-4f7e-bfda-be7028557bd2)

This is the data written by the equivalent [VGM file](https://github.com/jotego/jtcores/files/14000657/tnzs_0.vgm.zip)  from MAME

![imagen](https://github.com/jotego/jtcores/assets/1863036/60c5e8a7-3186-4007-9144-09eaf50fbbbd)

There seems to be a system-level problem. BTW, disabling the recovery for the Z80 prevents the system from booting up.
