### ISSUE TITLE
renegade: señal perdida

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#450]
Esta a la que le falta el driver tiene que LVBL, VB, o alguna derivación de estas

![imagen](https://github.com/jotego/jtcores/assets/1863036/e65a7931-2bd2-4f6a-a93f-e55f8064134d)

**Comment by etriana85** [comment]
La señal viene de los contadores verticales.
![#450a](https://github.com/jotego/jtcores/assets/92724765/0855a6fb-4714-4a04-a139-036dfa3e7c57)
![#450](https://github.com/jotego/jtcores/assets/92724765/beeca3fa-bf7c-47fb-a44a-7ca20c251819)

**Comment by jotego** [comment]
Gracias. Acuérdate de borrar la etiqueta que dice _driver?_ ahora que ya está claro.
