### ISSUE TITLE
Graphical glithches with bubble Bobble core (pocket)

### ISSUE THREAD

**Issue by mpatour** [jotego/jtcores#455]
Hi
As I reported on Patreon, I've encountered some graphical issues after the last update of Bubble Bobble core for the Analogue Pocket. Thoses glitches happen with Bubble Bobble and Scamble.
![01](https://github.com/jotego/jtcores/assets/142811869/5bfbaeba-ef93-4864-acf6-249f07f2945a)
![02](https://github.com/jotego/jtcores/assets/142811869/230034c9-5660-4b60-a893-7547d37901f3)
![03](https://github.com/jotego/jtcores/assets/142811869/2a81fede-dc0f-4c83-b7b9-b1b2d2a697d6)
![04](https://github.com/jotego/jtcores/assets/142811869/2f9ba6a3-7cdb-47d7-970c-31eedc960d1d)
![WhatsApp Image 2023-12-11 at 19 00 27](https://github.com/jotego/jtcores/assets/142811869/06b1e389-7e4f-4a20-9665-57ada8af6e63)

**Comment by jotego** [comment]
I think this is not the core's fault. I was expecting some marginal glitch in an advanced level. These glitches are very obvious and we would have caught them in our testing straight away.
I think there is something else going on here. Maybe the .rom files are not correct? The MRA files changed in the latest version and that required new .rom files generated. Make sure you have .rom and .rbf_r (core) files matched on the same version.

**Comment by jotego** [comment]
Sorry, you were right. This is specific to the Pocket version. The MiST version works ok, and that's the main one used for testing. I need to dig a bit into it to find out why the core gets this bug when compiled for the Pocket.

**Comment by stilltruckin** [comment]
Hi, I have the same graphic glitch with jtbubl core as pictured above.

**Comment by jotego** [comment]
- not related to the jtframe_dual_ram Pocket-specific code
- Only happens to the scroll layers, characters and objects are visible
- Tokio (M6805) affected too
- Only Pocket, MiST and simulation are fine
- A tile may be visible in the affected area and move with along the scroll

![20240115_204731](https://github.com/jotego/jtcores/assets/1863036/22122603-7a1f-4620-b7db-4627d831976b)

**Comment by jotego** [comment]
The graphics decoder PROM data (u_gfx.u_prom) is not loaded correctly in the Analogue Pocket.

The address does not get past FD, missing the last two bytes: FE, FF. Taking the header into account, the last 4 bytes are missing.

The problem comes from the **Analogue Pocket firmware,** which **does not handle file transfers correctly if the file size is not multiple of four.**

![image](https://github.com/jotego/jtcores/assets/1863036/49389fa5-b605-4e0f-9553-cf85ad10b8e9)
