### ISSUE TITLE
Analogue Pocket Gun Smoke: All ROMs Upside Down Except "Gun.Smoke (World, 1985-11-15)"

### ISSUE THREAD

**Issue by bebopjp** [jotego/jtcores#459]
Using jtgunsmk 1.5.0 on the Analogue Pocket (OS v1.2), all the ROMs pulled by Pocket Updater are upside down, except "Gun.Smoke (World, 1985-11-15)".

I noticed in some other JTCores running on Analogue Pocket, there is a "Flip Screen" option.  But in jtgunsmk, I can only see a "Rotate Screen" option.

**Comment by nortakales** [comment]
Simpsons is also upside down, with no core option to flip/rotate the screen

**Comment by jotego** [comment]
> The Simpsons (4 players World, set 1) is also upside down, with no core option to flip/rotate the screen. However, set 2 is NOT upside down. I did not check further ROMs.

Your system probably has an old and corrupted save file from an earlier version of the JTSIMSON core. Delete it and it will work.

**Comment by jotego** [comment]
About Gun Smoke, everything seems fine in commit f8166fbb. It must have been fine for a long time. I will update the files in JTBIN next Friday just in case that copy was bad.
