### ISSUE TITLE
JT74 KiCAD incorrectly inverted pin on LS241

### ISSUE THREAD

**Issue by antongale** [jotego/jtcores#460]
Pin 19 should not be inverted on the 74LS241

change this:

      (pin input inverted (at -12.7 -12.7 0) (length 5.08)
        (name "OEb" (effects (font (size 1.27 1.27))))
        (number "19" (effects (font (size 1.27 1.27))))
      )

to this:

      (pin input line (at -12.7 -12.7 0) (length 5.08)
        (name "OEb" (effects (font (size 1.27 1.27))))
        (number "19" (effects (font (size 1.27 1.27))))
      )

**Comment by jotego** [comment]
@etriana85 please check pin 19 of JT74's LS241

**Comment by etriana85** [comment]
I have checked the 74LS241 device datasheet, and pin 19 is active high. 
I have corrected the symbol in KiCad. Please pull to update the changes. 
![ LS241 #460](https://github.com/jotego/jtcores/assets/92724765/a21a2859-bf7c-4eae-8515-b0f8a8a4f555)
![460](https://github.com/jotego/jtcores/assets/92724765/8826004d-48cc-47dd-b0eb-68d932e9c02f)

**Comment by antongale** [comment]
Thank you!
