### ISSUE TITLE
Neo Geo Pocket: Option button is unmapped

### ISSUE THREAD

**Issue by davewongillies** [jotego/jtcores#477]
Some games use the `Option` button which is currently unmapped. Tested on the Analogue Pocket.

**Comment by davewongillies** [comment]
Metal Slug: 1st Mission. You use the option button to switch between firing  bullets and grenades

**Comment by jotego** [comment]
Thank you. The button is currently mapped to the arcade "1P". But knowing of this example, I suppose it makes more sense to have it as a regular button. I'll change it,

**Comment by jotego** [comment]
Actually, the option button was not connected indeed. Fixed in c0b10b15. I'll update the binary files later.

**Comment by davewongillies** [comment]
Just confirmed that this works on the Pocket with version 1.6.0 of the NGP core and Metal Slug: 1st Mission. Thanks!
