### ISSUE TITLE
Final Fight Continue game dip switch setting.

### ISSUE THREAD

**Issue by Dawbo66** [jotego/jtcores#481]
Not really an issue more of a Request but i wonder if the continue game option could be added into the Pocket version of Final Fight please, i have mentioned it also on Discord. Thank you.

**Comment by jotego** [comment]
**Technical notes**

The number of options displayable is heavily limited by the Pocket firmware. Some ways around this:

- Manually remove some options in the `mame2mra.toml` file
- Remove the version number from the options and add it to the Pause screen, that will open up one more slote

**Comment by jotego** [comment]
Fixed in 10e57e68
