### ISSUE TITLE
Add proper platform information in the jtngp.json for AP

### ISSUE THREAD

**Issue by alinanorakari** [jotego/jtcores#482]
Hello,

I'd like to propose replacing the data in the jtngp.json file in Analogue Pocket's Platforms directory with real data and the proper category for the platform. Since this metadata determines where the Analogue Pocket shows the platform and which details it shows for the platform, this would be much appreciated.

Instead of this

```json
{
	"platform":{
		"category": "Arcade compatible",
		"name": "jtngp",
		"year": 2022,
		"manufacturer": "JT FPGA"
	}
}
```

the new conttents of the file would be

```json
{
	"platform":{
		"category": "Handheld",
		"name": "Neo Geo Pocket",
		"year": 1998,
		"manufacturer": "SNK"
	}
}
```

The effects of this would be:
- When having Settings > Analogue OS > Group openFPGA turned on, the platform will show up in the category "Handheld" which cores for the oher handheld platforms also use, e.g. Spiritualized
- The label for the platform in the menu and the overview page would be named "Neo Geo Pocket" instead of "jtngp" fitting in better with the other properly named platforms
- It would show the details for Manufacturer and Release as "SNK" and "1998" which is in line with the rest of the handheld and console platforms

The proper technical information would still be visible when going to About on the platform page, showing its version number, the build date, "jotego" in the author field and "jtngp" as the core name.

Thank you in advance for considering it.

**Comment by alinanorakari** [comment]
An additional benefit of the change that I forgot to mention is that as soon as somebody else creates an NGP core it would show up in the "Change Core" option under the platform, like it already does e.g. for the Game Boy, which has both the core by Spiritualized, and another core by budude2 that has a different feature set (fast-forward via shoulder button but no save-states)

**Comment by jotego** [comment]
I am not changing the manufacturer nor the year as I am not SNK and I do not own the rights to do that. You are welcome to change that locally. 

I have changed the category to _Handheld_ as requested.
