### ISSUE TITLE
shouse: medir SNDIRQ respecto de VBLANK

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#487]
En Splatter House medir las señales SNDIRQ y /VBLANK simultáneamente para establecer la relación entre ellas. 

Página 15 del PDF

![imagen](https://github.com/jotego/jtcores/assets/1863036/d258c38c-c293-401f-a52a-007960e4fd7f)

**Comment by etriana85** [comment]
![SH_VB](https://github.com/jotego/jtcores/assets/92724765/cc55d5e5-03ce-4581-90a9-cea2eee7b101)
![SH_~VB_SIRQ](https://github.com/jotego/jtcores/assets/92724765/a9197bab-dde1-40e0-8d51-a90a43b44ca6)
![SH_SIRQ](https://github.com/jotego/jtcores/assets/92724765/901f8d9f-3e69-42c1-86eb-f2017c8f5bca)
