### ISSUE TITLE
When will the simpsons core be free?

### ISSUE THREAD

**Issue by Steven1977uk2002** [jotego/jtcores#488]
Whilst I appreciate the work you do any ideas when turtles and Simpsons will leave beta and be free to download? I don't mind paying a one off payment but monthly is a bit pricey for me

**Comment by jotego** [comment]
I am planning to add more games to those cores, that is why the beta phase has not finished. If you turn off the updates for JT cores in MiSTer or Pocket, the files in your device will remain playable. So you can stop your subscription and keep having access to the games indefinitely.
