### ISSUE TITLE
Odyssey: SEGA 315-0042 v1.0.1

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#489]
- [x] devolver la versión en master a la fabricada
- [x] arreglar la conexión de U16
- [x] arreglar el símbol de U17 en la librería jt74
- [x] revisar las conexiones VCC/VSS de los demás símbolos
- [x] arreglar la PCB
- [x] crear etiqueta en el esquemático para /VSYNC
- [x] eliminar las anotaciones **0 Y 1**
- [x] expandir la check list para verificar visualmente VCC y VSS en cada integrado
- [x] pasar las reglas y la check list
- [x] avanzar la versión a v1.0.2
- [x] etiquetar la versión en git

**Comment by etriana85** [comment]
![VCC_U16_315-0042](https://github.com/jotego/jtcores/assets/92724765/7b7db7a4-99f1-473d-b2fd-1431bedc0829)
![JT74LS174_315-0042](https://github.com/jotego/jtcores/assets/92724765/8c7dcde9-d745-4706-bfd2-70dbeb37776f)
![IGN_PCB_315-0042](https://github.com/jotego/jtcores/assets/92724765/66c641ca-9e11-4b20-ae80-1b698689f647)
![erc 315-0042_1](https://github.com/jotego/jtcores/assets/92724765/d7a4cec0-c607-4468-bc38-18099616c2f1)
![erc 315-0042](https://github.com/jotego/jtcores/assets/92724765/a18f8f2d-6977-43e0-a7ca-5eda5ac176e7)
![ECR_PCB_315-0042](https://github.com/jotego/jtcores/assets/92724765/3e05955c-cf17-427e-956c-088c87963470)
![~VS_315-0042](https://github.com/jotego/jtcores/assets/92724765/12af1620-b1d8-4ba7-abee-54169182639c)
![sch_315-0042](https://github.com/jotego/jtcores/assets/92724765/8c0a2e16-030f-4088-8a5b-0b1cf1fc0e58)
![FECHA_315-0042](https://github.com/jotego/jtcores/assets/92724765/b33de68e-9622-4567-8379-f7d14e75c934)
![custom 315-0042 v1 0 2](https://github.com/jotego/jtcores/assets/92724765/3f59e7f8-a2ce-49fc-9bd6-2a0aa94b501f)
![VER 1 0 2_315-0042](https://github.com/jotego/jtcores/assets/92724765/fc9dd19e-fb65-4487-b76b-cb0eb4c8e347)
![u17_315-0042](https://github.com/jotego/jtcores/assets/92724765/f7601c47-4bee-4326-bcce-3f8dead91df6)

**Comment by etriana85** [comment]
![Lista de chequeo](https://github.com/jotego/jtcores/assets/92724765/d701d837-7da0-464b-b911-c44a184db3d2)

**Comment by etriana85** [comment]
![Lista de chequeo](https://github.com/jotego/jtcores/assets/92724765/cc6c2ae9-17f3-4c29-b881-d07f04c4b0d9)
![clu](https://github.com/jotego/jtcores/assets/92724765/7c39d65d-6c8b-4de1-88b7-98214620ae7e)
