### ISSUE TITLE
roadf: Hyper Sports buttons issue

### ISSUE THREAD

**Issue by olli4711** [jotego/jtcores#501]
can not setup buttons to have a convenient gameplay.
The original game has two "Go" buttons and an "Up" button per player (https://strategywiki.org/wiki/Hyper_Sports)
When defining hypersport buttons in core menue it asks for: RIGHT, LEFT, DOWN, UP, Left button, Centre button, Right button, Start, COIN, Core credits
I can get a 1 Player game working using UP, DOWN, RIGHT buttons.
2 Player mode is not working with this setup as second player seems to constantly press DOWN

In the MRA it shows:     buttons names="Left button, Centre button, Right button,Start,Coin,Core credits" default="Y,X,B,Start,Select,-" count="3"

**Comment by jotego** [comment]
Hyper Sports was not being identified correctly by the core so the Road Fighter inputs were applied instead.
Fixed in a5283c6
