### ISSUE TITLE
CPS1: gulunpa high-pitched noise continues (MiSTer)

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#504]
CPS1: gulunpa high-pitched noise continues
commit: e444aef

**Comment by jotego** [comment]
Trying older versions of JT51:

- https://github.com/jotego/jt51/commit/898faf289488acf5a7d12df9062a814966b75158 fails
- https://github.com/jotego/jt51/commit/65c927a fails

Not a problem of recent changes to JT51, apparently. MAME does not show this issue.

**Comment by jotego** [comment]
![imagen](https://github.com/jotego/jtcores/assets/1863036/ca04f32c-a0b4-41aa-a0f4-8a57320662e7)

Tone at 1156 Hz (period 405.6us)

**Comment by jotego** [comment]
The noise comes from the PCM channel, even before the pole filter and the interpolator.
