### ISSUE TITLE
ROADF: Hyper sports sounds garbled (POCKET)

### ISSUE THREAD

**Issue by Dawbo66** [jotego/jtcores#516]
The speech in hyper sports ( pocket ) sounds like the commentator is under water and not understandable, sounds very garbled.

**Comment by jtmiki** [comment]
Core | game | issue |
----|---|-----------|
roadf | hyper sports | sounds like the commentator is under water and not understandable, sounds very garbled. |

commit: 48980d9

**Comment by jotego** [comment]
Related to #136

**Comment by jotego** [comment]
I have implemented the software-controlled filters that the board has. Not with the exact cut-off frequency but with a noticeable effect. In the future, when I tackled #402, I will look into implementing the exact filter bandwidth. 
Done in 414e5cf

**Comment by jotego** [comment]
The cheering at the end of the swimming competition sounds distorted. There is no clipping indicated by the LED. Commit fcfa7dfe

**Comment by jotego** [comment]
seems fine in a1ffbab

**Comment by jotego** [comment]
The _audio_ section of the mem.yaml was using `unsigned` instead of `dcrm` for the resistor DAC channel. Hence, the dc component was not removed.
