### ISSUE TITLE
parodius: renombrar o borrar linea BRIT

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#517]
La salida **BRIT** en colmix se confunde con la entrada **BRIT[2..0]**. No hay que duplicar el nombre de señales distintas. Los esquemáticos están ahora dentro de `simson/sch/parodius`, porque parece que el juego puede compartir core con _The Simpsons_

Hay un puente para conectar a VSS algunos pines del J15, pero la forma de representarlo en el esquemático no deja clara la conexión. Lo que llegue a VSS a través de JP6 debería conectar sólo a JP6 y no a JP6 más VSS.

![imagen](https://github.com/jotego/jtcores/assets/1863036/99b2450b-af8c-4081-a8de-42ca50fbc45d)

El símbolo del 053245 (J11) está anticuado respecto de la biblioteca. En Asterix es distinto. Todos los sch que usen el mismo dispositivo tienen que usar la versión actual del símbolo para poder compararlos y poder completar los nombres de pines entre todos.

**Tareas:**
- [x] Renombrar el cable **BRIT** o borrar si no va a ningún sitio.
- [x] El puerto **BRITEN** de colmix también parece redundante, borrarlo y dejarlo como señal interna
- [x] Renombrar pin `~SOUND` a `SOON` (de _sound  on_) en todos los niveles, como se ve en los sch. de los simpson
- [x] Igualmente renombrar pin `~MCS` a `SOREG` (de _sound register_) 
- [x] Identificar qué pines conectan a VSS a través del puente y cuáles no
- [x] Renombrar el pin AS del 053248 a ~{AS}, así como la señal AS en main llamarla ~{AS}. Ojo porque la salida de H21B hay que renombrarla de ~${AS} a AS, así como en F19A/B y H22A
- [x] Las señales SCRCEL y SCRCEH en colmix y rgb (parodius) no deberían llevar el prefijo SCR sino PAL o COL o CO como en el resto de la hoja.
- [x] Actualizar símbolo del 053245 a la versión de la biblioteca (la que usa Asterix)
- [x] Volver a pasar las reglas de diseño

**Comment by etriana85** [comment]
![#517SO](https://github.com/jotego/jtcores/assets/92724765/3007e21c-de73-40a3-9fd5-7598bf26b763)
![#517OS](https://github.com/jotego/jtcores/assets/92724765/129e5781-ec00-4f0c-af55-5ce58f2746cb)
![#517O](https://github.com/jotego/jtcores/assets/92724765/df2105a0-eaf9-4407-bb6c-f23f7b988dc3)
![#517MA](https://github.com/jotego/jtcores/assets/92724765/5345a5d2-9b7a-4205-996c-fd3a0ae9224e)
![#517BRI](https://github.com/jotego/jtcores/assets/92724765/7353a12b-5bfc-491b-b957-98495d55babe)
![#517](https://github.com/jotego/jtcores/assets/92724765/4806cbb9-2b7a-4c44-a05d-4cf666c384d0)

**Comment by etriana85** [comment]
A continuación adjunto una imagen del orden del bus de datos que viene de _main_. Es el custom 053248, su diseño está basado en información de la web [https://twitter.com/RndMnkIII/status/1220309920001732608](url) y en la extracción del sch. 
El punto es que no coincide el orden del bus al pasar por la RAM.
![#517main](https://github.com/jotego/jtcores/assets/92724765/c8e1beb8-a1dd-494b-b36a-2618a44ce46b)

**Comment by etriana85** [comment]
![#517jum](https://github.com/jotego/jtcores/assets/92724765/c51e561f-533f-4143-a066-fb60addb2b18)
![#517colmix](https://github.com/jotego/jtcores/assets/92724765/e2af0f87-3290-4892-b5cf-996531426cbd)
![#517brit](https://github.com/jotego/jtcores/assets/92724765/3bab33a2-03c8-4623-876b-2a9cd0943de2)

**Comment by jotego** [comment]
Que no coincida el orden en el custom con la memoria no tiene consecuencias funcionales pero fue mala práctica por parte de los diseñadores.
