### ISSUE TITLE
simson: bus MAIN_A corrido una posición en colmix

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#518]
MAIN_A está conectado desde A0 en adelante a los multiplexores, debería empezar en A1 como ocurre en Parodius. Fíjate que A0 entra por otro lado para controlar la escritura. No tiene sentido que entrase a la vez por la dirección. Corrígelo para que sea como en Parodius. El bus de direcciones de la RAM de color debería empezar en 1 también, como en Parodius, al ser una memoria de 16 bits (formada a partir de dos de 8 bits)

Acciones:
- [x] Reconectar main_a empezando desde MAIN_A1 en vez de MAIN_A0 a los multiplexores
- [x] Renombrar MCOL0..10 a MCO1..11 como en Parodius

![imagen](https://github.com/jotego/jtcores/assets/1863036/b677cf08-9486-4af5-afe5-614e6d84e15d)

**Comment by etriana85** [comment]
![#518MIX](https://github.com/jotego/jtcores/assets/92724765/75a11948-91ca-43f8-b775-589e5b6ea792)
