### ISSUE TITLE
not possible to coin up anymore in bubble bobble on analogue pocket

### ISSUE THREAD

**Issue by tmerelle** [jotego/jtcores#520]
Hi Jotego,

Hope you are doing well. And many thanks for the amazing work you are doing on FPGA recreation!

I wanted to let you know that since yesterday's last update of your jt cores, I cannot anymore add credits to bubble bobble on my analogue pocket.

Cheers,

Thomas

**Comment by redsteakraw** [comment]
I want to add the same bug is on the MiSTer FPGA with the Simpsons and TMNT cores.

**Comment by jotego** [comment]
Just retested all three games and they all operate correctly. Please read this sort [FAQ](https://github.com/jotego/jtbin/wiki/Why-I-only-see-the-on-screen-credits%3F)
