### ISSUE TITLE
Exed Exes: is second background correct?

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#531]
Some tiles in the background do not look right. Compare with PCB in second stage.

![20240202_134951-screen](https://github.com/jotego/jtcores/assets/1863036/675748c0-1d3f-4d49-80be-b75b5e23346e)
![20240202_135011-screen](https://github.com/jotego/jtcores/assets/1863036/1d9ccab3-fe4f-419b-a64a-782cda21b340)
![20240202_134556-screen](https://github.com/jotego/jtcores/assets/1863036/22caaf52-883a-4ebd-b2a9-97b02c02d5ae)
![20240202_134819-screen](https://github.com/jotego/jtcores/assets/1863036/979058b0-a195-4eac-ab4c-ffdf8fdd2201)
![20240202_134851-screen](https://github.com/jotego/jtcores/assets/1863036/2ecae185-c40c-4345-935b-02b635196fb5)
![20240202_134942-screen](https://github.com/jotego/jtcores/assets/1863036/cb73e677-fe6e-4fb5-b707-f7ef62badcff)

**Comment by etriana85** [comment]
II have reached level 4, and I never saw the background that appears in the attached images. I checked on youTube a video that seemed to be played from the board (video 1) by the quality of the video, and another one that had the title "mame" (video 2) and I don't see those backgrounds either. In the third video the background does appear. The background appears at minute 1.21, very close to the time of the video I made playing from mame (min 1.16). You start to see the red background (of the images where the error is, and that you see in the video 3), just after the hornet appears. I would think that there is another version or maybe a bootleg. 
![exedyouTuberojo](https://github.com/jotego/jtcores/assets/92724765/40deb958-3b46-4f51-9241-1ded57fdaf88)
![exedmamejt](https://github.com/jotego/jtcores/assets/92724765/119134cc-5be3-4c16-add0-0adbeb7ae344)
![eeyouTuberojo](https://github.com/jotego/jtcores/assets/92724765/29e741bf-c123-4768-9794-2b9143627db7)
![eejtmame](https://github.com/jotego/jtcores/assets/92724765/123d0285-5990-4166-8bda-e3a6737b081d)
![eeytrojo](https://github.com/jotego/jtcores/assets/92724765/a9cfa160-d281-44ae-8db2-8ac98b618bda)
![eejt](https://github.com/jotego/jtcores/assets/92724765/0d53f387-698d-4db7-b8bd-4d026116fbc5)


YouTube 1
https://youtu.be/V3uHGUwXJJg?si=3rhyktErPJEMkwOQ
YouTube 2 mame
https://youtu.be/MUhQSXOLCeA?si=ugvVBxX6tr4UhOcJ
YouTube 3*
https://youtu.be/tFCtTBNRR_M?si=kSVCyvIDWWtcJ_-z

**Comment by jotego** [comment]
The code was designed after a bootleg PCB. @etriana85 thinks that the bootleg had different backgrounds. Maybe the second background tile codes are different?

**Comment by gyurco** [comment]
It acts as a completely different layer from stage 2, strange. Maybe issue with the map addressing?

**Comment by gyurco** [comment]
A good point to compare:
https://youtu.be/tFCtTBNRR_M?t=133

**Comment by jotego** [comment]
In that video the land around the red river looks well shaped, whereas in the core it has sharpen edges as though the tiles were not flipped correctly

**Comment by gyurco** [comment]
Seems not just flip, but wrong tile also, see the river on the left middle, around the skull.

**Comment by gyurco** [comment]
Well, in MAME, there's not even a river at this place.

**Comment by gyurco** [comment]
Maybe rom2_data is not always ready at heff[3:0]==0?
There's no check for rom2_ok.

**Comment by jotego** [comment]
> Well, in MAME, there's not even a river at this place.

I could not see the river either in MAME. Our board is not booting up anymore (these old PCBs are not reliable at all) so we cannot test it there.

**Comment by jotego** [comment]
The river scene is fixed after the PR. Thanks @gyurco 
![20240210_075635-screen](https://github.com/jotego/jtcores/assets/1863036/a2ecaa3b-4d3f-4cfd-9ad3-1a1e3c00e752)
![20240210_075618-screen](https://github.com/jotego/jtcores/assets/1863036/73683a36-b768-4754-9b16-4925dcd0064d)
![20240210_075426-screen](https://github.com/jotego/jtcores/assets/1863036/19caf622-c110-40a3-a906-6e78581182ea)
![20240210_075439-screen](https://github.com/jotego/jtcores/assets/1863036/6c95e5f1-2b1c-447a-8f4a-f4ff73f17799)
![20240210_075550-screen](https://github.com/jotego/jtcores/assets/1863036/10b20655-0c34-4fc7-94a9-ea49ef037586)
![20240210_075602-screen](https://github.com/jotego/jtcores/assets/1863036/292d7d19-23c1-47ae-ab34-2009a2274d8a)
