### ISSUE TITLE
Recursive git not working... 

### ISSUE THREAD

**Issue by ducasp** [jotego/jtcores#532]
Hi,
It seems recursive is not getting anything on modules other than the folder names... It seems that git fails because jt900h ( https://github.com/jotego/jt900h/tree/e4ab1cdec96b850578c0f86242b9138b7281a70b ) and  that cause git to stop recursing...
If I click jt900h with my user logged in or without any login, I receive a 404 page

**Comment by jotego** [comment]
Yes, because of two private models, the first time you initialize the repository you will need to do kind of a manual update. After that, you'll be able to run `git submodule update` correctly.
