### ISSUE TITLE
Blades of Steel schematics

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#534]
Extract schematics for _Blades of Steel_ PCB

**Comment by etriana85** [comment]
Okay, do we need the extraction before or after The Fairyland Store?

**Comment by etriana85** [comment]
Contamos con el sch en PDF. 
[KONAMI Blades of Steel.pdf](https://github.com/jotego/jtcores/files/14165674/KONAMI.Blades.of.Steel.pdf)
