### ISSUE TITLE
parodius: renombrar LDS a A0

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#537]
La línea **A0** tiene el nombre `~{LDS}`. Debería mantenerse **A0** en main. Tiene sentido mantener **A0** en todos los esquemáticos en el caso de Parodius. **LDS** es un nombre que se usa en memorias y procesadores de 16 bits, pero ese no es el caso aquí.

- [x] Renombrar `~{LDS}` a `A0`

![imagen](https://github.com/jotego/jtcores/assets/1863036/4a19e782-e58e-4770-b191-49b100c3779e)

**Comment by etriana85** [comment]
Corregido.
![ISSUE#537](https://github.com/jotego/jtcores/assets/92724765/6ee7521f-be57-4834-8ee3-82c0e195dd3e)
