### ISSUE TITLE
shouse: blastoff support

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#544]

**Comment by jotego** [comment]
@gyurco this was the issue for missing games in shouse core

**Comment by gyurco** [comment]
Here's the PR for the games to start:
https://github.com/jotego/jtcores/pull/587

You don't have to search for the video issues, it'll come as you boot a game. Splatterhouse might be a very good boy to work so good, the others must be the nasty ones.

**Comment by jotego** [comment]
Absolutely, the video problems are all over the place. It is almost a miracle Splatter House looks that good!

I'll close this issue and open specific ones if I find a boot or stability problem in a game.
