### ISSUE TITLE
kicker: kicker boss invisible

### ISSUE THREAD

**Issue by joxheaf21** [jotego/jtcores#545]
After kicker was integrated into gng it is not playable since the bosses are blinking or are not visible at all.

**Comment by jotego** [comment]
Confirmed in 5c84ab6
The first level boss is good, but the second level boss blinks constantly

**Comment by jotego** [comment]
Turning recovery off in the CPU does not fix it.

**Comment by jotego** [comment]
The PROM start was wrong in _macros.def_. Will update the files next Friday.
