### ISSUE TITLE
vendetta: encontrar conexiones a los chips de objetos

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#547]
En la hoja de IO del esquemático de Vendetta hay una señal llamada **NCPU**. Esta señal debe venir de uno de los dos chips de objetos. Localízala, por favor, y añádela a los esquemáticos en simson/sch/vendetta

![imagen](https://github.com/jotego/jtcores/assets/1863036/0ad06aa7-ecf2-47f4-901d-0e04e0fa6ce0)

La señal **CRCS** en la hoja de la CPU también va a los objetos. Localízala, por favor.

![imagen](https://github.com/jotego/jtcores/assets/1863036/15ce95fc-f595-4bdc-a8ee-e8bcfecbfc08)

Verficiar que realmente CAB2 del G13 acaba en el pin COL7 del J13

![imagen](https://github.com/jotego/jtcores/assets/1863036/2a4e6cb0-a790-433b-8942-e1af21a7a9e2)

Para hacerlo más fácil, llama a las señales que entran a la ROM I16 GFXROMA, sin añadir la B nunca. Para las señales que van de COLx a H8, puedes mantener el nombre COLx que tiene el pin directamente. Así se lee más claro mirando H8. Porque ahora salen de COL llamándose GFXROMA13 y acaban en el pin A15 de la GFX ROM, y eso es confuso. 

![imagen](https://github.com/jotego/jtcores/assets/1863036/f1f9285c-5cbe-4d1f-a9a9-fab9047240e8)

La RAM marcada como J1 es en realidad I1 en la PCB

![imagen](https://github.com/jotego/jtcores/assets/1863036/581b0023-08de-43ea-afc7-113c3c72fdef)

**Comment by etriana85** [comment]
![#547A](https://github.com/jotego/jtcores/assets/92724765/dca410fd-76a0-4d49-a484-ce197e25e92a)
![#547](https://github.com/jotego/jtcores/assets/92724765/bcaa8085-9217-47e2-be9d-add57d0b63a5)

**Comment by etriana85** [comment]
- [ ] Verficiar que realmente CAB2 del G13 acaba en el pin COL7 del J13
Sí, la señal *COL7*, pasa por el buffer *H8* y llega al pin 107 del *J13*

- [ ] Para hacerlo más fácil, llama a las señales que entran a la ROM I16 GFXROMA, sin añadir la B nunca. Para las señales que van de COLx a H8, puedes mantener el nombre COLx que tiene el pin directamente. Así se lee más claro mirando H8. Porque ahora salen de COL llamándose GFXROMA13 y acaban en el pin A15 de la GFX ROM, y eso es confuso.
Así esta bien?
![#547_COL](https://github.com/jotego/jtcores/assets/92724765/41ea8187-9717-44c8-9eb9-85ff75ed33bb)

**Comment by etriana85** [comment]
La ROM I1 de vendetta, está bien marcada en el sch. Será que ya la corregiste?. Pero me causa curiosidad que no coincida la OR que tiene al lado, ni el nombre de la señal A0.
![#547_rom](https://github.com/jotego/jtcores/assets/92724765/434396f6-1084-446d-9694-905446c4a41a)

**Comment by etriana85** [comment]
Ésta es una fotografía de la PCB de los Simpsons, será que te refieres a ésta?
La RAM de los Simpsons tiene la ubicación 1J
![#547_J1](https://github.com/jotego/jtcores/assets/92724765/3bd205a1-86fc-459f-af12-b907f8b87583)

Lo que si veo es que dejé por defecto de KiCad el orden del nombre de las diferentes ubicaciones,  *letra y número*. En éstas PCB el orden es, *número y letra*. Ya me dices si lo corrijo todo.

**Comment by jotego** [comment]
¿cuál es el _driver_ de **DS**?

![imagen](https://github.com/jotego/jtcores/assets/1863036/f492c591-69f6-4850-b8a0-87fcf692a26d)

**Comment by etriana85** [comment]
Página 13 del sch The Simpsons
![#547ds](https://github.com/jotego/jtcores/assets/92724765/0693ecf9-12c5-4b57-b9e1-62ad5732dbb7)
