### ISSUE TITLE
Vendetta: Bug Report [vfbb89f0]

### ISSUE THREAD

**Issue by Toryalai1** [jotego/jtcores#552]
Platform: MiSTer
Core version: vfbb89f0
Setname: vendetta2pp
Video reference: https://www.youtube.com/watch?v=z9skP9BRvDU

General:
- During stage transition, when going from stage 1-1 to 1-2, there is some graphical garbage during the blackout. Difficult to do a screen dump since it happens fast. This happens on all black out transitions 

- Rom check shows BAD:
![image](https://github.com/jotego/jtcores/assets/82502378/2d02cb45-f8d5-4434-a7b1-65be818b7bef)

Stage 2:
- Floating cranes are appearing randomly:
![image](https://github.com/jotego/jtcores/assets/82502378/26e6af78-9c10-4c05-aeea-0acd49aebaf2)

Stage 4
- Boat and anchor have sprite tearing
![image](https://github.com/jotego/jtcores/assets/82502378/6dc43720-abe7-409c-93ee-9726be5f2a29)

Also the platform after defeating the boss is following boat movement:
![image](https://github.com/jotego/jtcores/assets/82502378/97b31ee6-820a-47b7-b59d-63cfd8eb3303)

Stage 5
- Sign gets stuck on player 
![image](https://github.com/jotego/jtcores/assets/82502378/0bfa2b46-1c34-4230-a0b3-93d7bcb34161)

- Two enemies should be out of view:
![image](https://github.com/jotego/jtcores/assets/82502378/8bfa29cf-a143-49f0-bd7b-f4fc70bf1907)

Thank you for your hard work and developing these amazing cores

**Comment by michelefornasini** [comment]
In the second part of the second level, when you enter the elevator that goes down, the 2 enemies that jump from above and try to hit you reappear below.

**Comment by jotego** [comment]
The ROM check was implemented as part of #557. It is working in 8028053.

**Comment by jotego** [comment]
It looks like it all came down to subtracting the object vertical offset rather than adding it. I have corrected it. Could you check this MiSTer core to verify the fix?

[jtsimson.rbf.zip](https://github.com/jotego/jtcores/files/15006821/jtsimson.rbf.zip)

Please also have a look at _The Simpsons_ and _Parodius Da_ in case this fix caused trouble there.
