### ISSUE TITLE
btiger: Screen not blanking during transitions

### ISSUE THREAD

**Issue by BMF54123** [jotego/jtcores#560]
During certain screen transitions, the core is not completely blanking the screen as it should. For example, when transitioning from the high score screen to the gameplay demo, the "Black Tiger" logo remains onscreen; on both my bootleg PCB and in MAME, the entire screen goes black until the demo starts (also confirmed on a friend's authentic Capcom PCB).

**Comment by jotego** [comment]
There might be a _video enable_ signal missing. I will check it.

**Comment by jotego** [comment]
All three control bits for video signals are set low, but the char layer remains on screen

**Comment by jotego** [comment]
Thans for spotting this, @BMF54123. This is fixed now and I will release it in the next JTFRIDAY update.
