### ISSUE TITLE
jts16/Shinobi - player is 1 pixel too high.

### ISSUE THREAD

**Issue by jonxs1976** [jotego/jtcores#564]
Player is 1 pixel too high, more noticable when on the upper level, this only happens with the following .mra's, the other .mra in the _Alternative folder seem correct.

**_Arcade**
Shinobi (Set 6, World, S16A) [No Protection].mra

**_Alternative**
Shinobi (Set 1, World, S16A) [FD1094 317-0050].mra

![Screenshot 2024-03-02 131448](https://github.com/jotego/jtcores/assets/80528271/1f9d2e11-0a1f-486d-a09d-d29fd834a91c)

**Comment by jotego** [comment]
Can you provide a non-emulated image with the right position?

**Comment by jotego** [comment]
Objects are off by one pixel in S16 core with respect to S16B apparently.

**Comment by jotego** [comment]
The object layer misalignment is clearer in the S16A version of WB3

![20240407_163620-screen](https://github.com/jotego/jtcores/assets/1863036/17a142cb-b238-46c1-8f9c-1dfa96e85658)

**Comment by jotego** [comment]
Fixed. I'll release the update soon.
