### ISSUE TITLE
OUTRUN - car always steers to one side when Pocket is in the HDMI Dock

### ISSUE THREAD

**Issue by NeilGSPGUK** [jotego/jtcores#567]
when using the Pocket with HDMI Dock and a Stadia BT Controller, or wired xbox360 controller the left analog thumb stick has to be held at max LEFT or max RIGHT to be able to steer correctly from the D-Pad.

So somehow the input is registering full steering lock to either Left or Right when there is an analog thumbstick controller used.

**Comment by jotego** [comment]
Thanks for reporting it. This is already reported in #384 so I will close this one
