### ISSUE TITLE
Bubble Bobble - Cannot insert coin

### ISSUE THREAD

**Issue by NeilGSPGUK** [jotego/jtcores#568]
Coin input not registering in latest core release for Bubble Bobble ROMS, works fine for TOKIO ROMS, rolled back to previous core in Coin Input works OK in Bubble Bobble.

**Comment by jotego** [comment]
Try deleting old saving files or check the DIP settings for Bubble Bobble. The two games operate on the same core, so they should work well.
I have double checked using a fresh SD card and I can start a game normally.
