### ISSUE TITLE
Outrun arcade with the last cores missing car

### ISSUE THREAD

**Issue by gekko1979** [jotego/jtcores#571]
The last core working for me is in the download of this post 01 05 24:

https://www.patreon.com/posts/95909155?utm_campaign=postshare_fan

other most new core the car is missing.
Someone like me? I know is not for all user and this is strange, possible hardware different revisions?
Thanks.

**Comment by jotego** [comment]
This is duplicated in #391 , please subscribe to that issue as I will be uploading cores for testing to it

**Comment by hansfbaier** [comment]
I have the same issue on the MiSTeX port.
What was the fix? I cannot see any commit attached to this issue.
