### ISSUE TITLE
tora: comparar circuito en esquemático con placa F1-Dream

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#576]
El circuito del MSM5205 podría ser diferente en la placa de F1-Dream. 

- Determinar el valor de R13 (pág 9)
- Comprobar si el pin 5 del amplificador 13B conecta al punto M realmente (pág 9)
- Verificar el valor de R30 y R31 (¿58k?) (pág 8)
- Verificar el valor de C45 (¿1nF?) (pág 8)

En la página 8, hay un _resistor _array_ de 1kOhm, RA4?, y otro. ¿cuál es el valor y el esquema de las conexiones en el _resistor array_ de la derecha?

![image](https://github.com/jotego/jtcores/assets/1863036/822ea30c-c808-41c7-856f-8a219ea2eb48)

**Comment by etriana85** [comment]
R13 está ausente o fue cortada en la PCB F1 
![tora#576](https://github.com/jotego/jtcores/assets/92724765/9cebbe29-33b9-4dcf-b465-733864464eb3)
![f1#576](https://github.com/jotego/jtcores/assets/92724765/8fc92c01-be64-4b52-b7cc-a1e09aa69db8)

**Comment by etriana85** [comment]
- [ ] Comprobar si el pin 5 del amplificador 13B conecta al punto M realmente (pág 9)  **Sí**
- [ ] Verificar el valor de R30 y R31 (¿58k?) (pág 8)  **56k**
- [ ]  Verificar el valor de C45 (¿1nF?) (pág 8) **Sí**
- [ ] En la página 8, hay un _resistor array de 1kOhm, RA4?, y otro. ¿cuál es el valor y el esquema de las conexiones en el     resistor array de la derecha? **56k**

![ra56k](https://github.com/jotego/jtcores/assets/92724765/2cd0da42-d999-4611-b122-5aab573ef4c4)

**Comment by jotego** [comment]
Gracias. Sobre el _resistor array_ me refería a este bloque de puntos:

![image](https://github.com/jotego/jtcores/assets/1863036/11e301cd-cfe2-492e-95cc-92b6391b4dbb)

Necesito saber qué estructura de resistencias hay dentro.
