### ISSUE TITLE
exed: frecuencia de corte del filtro

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#577]
Este cálculo está mal

![image](https://github.com/jotego/jtcores/assets/1863036/ab460de6-d42e-4e95-b86d-3f572fe3fb2b)

El cálculo correcto sería:

- asumir que el SN76489 (nuestro **jt89**) tiene salida de corriente y no de voltaje
- si es de corriente, la rama R49/CP158 no puede ignorarse
- El condensador CP153 es tan grande, que es como un cortocircuito 
- CP158 forma un filtro paso baso y la resistencia que se ve desde el condensador es 10 kΩ+10 Ω ≈ 10 kΩ ➩ fcut = 1/(2πRC)=1.6kHz

Esto encaja con la [simulación](https://www.circuitlab.com/editor/#?id=7qmsz9u5rsnh)

![image](https://github.com/jotego/jtcores/assets/1863036/ec51a10b-753e-4352-baf7-822a5e507892)

- [x] Corregir la anotación en el esquemático

**Comment by etriana85** [comment]
![exed #577](https://github.com/jotego/jtcores/assets/92724765/56132360-190e-40bf-b3f6-ceaf4f980c49)
