### ISSUE TITLE
kicker: condensador demasiado grande

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#578]
Los condensadores CC10 y CC12 están marcados como 104M, lo que indica 100nF±20%. 100nF es demasiado. Saldría una frecuencia de corte para el filtro de 200Hz ([simulacion](https://www.circuitlab.com/editor/#?id=s82443x933gq)). Revísalo en la placa. Comprueba también las resistencias y el otro condensador que forman el filtro.

Resimula con los nuevos valores. Esperaría que la frecuencia de corte estuviera en el rango 2-20kHz. Esto afecta también al Ping Pong. Actualiza los esquemáticos de Ping Pong y Kicker con los nuevos datos.

![image](https://github.com/jotego/jtcores/assets/1863036/0f28716b-4b6b-4019-8863-1a621256f4cb)

**Comment by etriana85** [comment]
Condensadores:
CC10, CC12 104K  (100nF±10%)
R21, R24 10 

Los filtros:
R20, R23 1K
Cp 47nF 
![#578 kicker](https://github.com/jotego/jtcores/assets/92724765/711178af-4b38-4866-80f0-adc07254f33e)

**Comment by etriana85** [comment]
![kicker#578](https://github.com/jotego/jtcores/assets/92724765/9172f6a0-6336-4832-8460-19a689645a0c)

**Comment by etriana85** [comment]
He puesto el mismo valor de kicker,  a los condensadores de pin pong.aa
![pp #578](https://github.com/jotego/jtcores/assets/92724765/b416391c-4865-44a2-a7fc-c423c3b2e39d)

**Comment by etriana85** [comment]
![pp2 #578](https://github.com/jotego/jtcores/assets/92724765/a8725259-c6aa-4145-b772-f0dad99a2fbc)
![pp1 #578](https://github.com/jotego/jtcores/assets/92724765/dfd51ab2-ed48-433a-8941-a90e807483cb)
