### ISSUE TITLE
Outrun: Blue Line on Left Side of Screen on Music Select + Rear Tail Lights Flicker and Vanish

### ISSUE THREAD

**Issue by Jlmbles** [jotego/jtcores#585]
Flickering Tail Lights which eventually turn grey. Also a thin blue line on the left side of the screen when selecting a music track.
![PXL_20240322_002956436](https://github.com/jotego/jtcores/assets/140926648/7b44ef8c-b6e7-4788-ba81-337eb30b768c)

**Comment by Dawbo66** [comment]
@jotego when you press the break button the back lights at the top go see through and its the road your seeing through the lights, so the flickering is actually the white lines on the road, the back lights should be solid, when the break lights come on at the bottom the top lights go see through.. So to recreate drive over the white lines and break ,you'll see the lines where the top lights should be..

**Comment by Dawbo66** [comment]
@jotego when you press the break button the back lights at the top go see through and its the road your seeing through the lights, so the flickering is actually the white lines on the road, the back lights should be solid, when the break lights come on at the bottom the top lights go see through.. So to recreate drive over the white lines and break ,you'll see the lines where the top lights should be..Even when going fast on a bend and press the break you can see the white road lines as you go over them. sorry about the crude drawing..😊
![RetroArch outrun](https://github.com/jotego/jtcores/assets/133606938/ce7be140-9c78-4e9e-9a87-b86b7572f543)

![1000006230](https://github.com/jotego/jtcores/assets/133606938/0ac1e325-f0c0-4c89-bb02-6a47caf34f78)
![1000006231](https://github.com/jotego/jtcores/assets/133606938/8ee0f6e3-1190-4437-987b-f2765413b7b1)

**Comment by Jlmbles** [comment]
Also this seems to trigger at the first checkpoint.

**Comment by jotego** [comment]
Thank you for the detail screen shots. I can see the problem with the rear lights when the brakes are on. I cannot see the blue line mentioned in the issue title, though.

**Comment by jotego** [comment]
Fixed the rear lights by removing a piece of logic in colmix derived from the PAL dumps that did not make quite sense. See d7cdc1b1

**Comment by jotego** [comment]
Blue line fixed in f3c11490 by adjusting the tilemap position.
