### ISSUE TITLE
Analogue Pocket Gun Smoke: The stage select cheat doesn´t work.

### ISSUE THREAD

**Issue by Wraalf** [jotego/jtcores#586]
According to the README:
"If you enable the test mode after the game has already started, 
it is possible to start at any level by altering the value of the coin slot settings."

**Comment by jotego** [comment]
The way the DIP switches are implemented in the Pocket version imply a system reset when a DIP value changes. It is done that way to simplify the user experience (as almost all games only read DIP values during reset) and also to avoid having an explicit "RESET" line in the OSD menu. The number of lines allowed in the menu is very short, so skipping that RESET is a good tradeoff.
Overall this means that this feature is not supported on the Pocket version. Sorry.
