### ISSUE TITLE
Pang (World) - Graphical glitch on the ladders

### ISSUE THREAD

**Issue by Urotsukidoji** [jotego/jtcores#588]
Hi there!

  Several people, included me, have seen what it seems to be a graphical glitch on the game Pang (World). 
  On the screens where a ladder/s appear, in the left ladder appear a little strange green object.

  Cheers.

**Comment by jotego** [comment]
Please attach a screenshot if you have one handy

**Comment by Urotsukidoji** [comment]
Sure, 

    Here's an image.

 Cheers (S
![PANG photo_2024-03-25_18-36-00](https://github.com/jotego/jtcores/assets/90918114/b9b95cab-1db9-4949-997d-690b66597abe)
aludos)

**Comment by vastago** [comment]
Además de las escaleras está el tema del efecto de sonido cuando rompes las bolas, se escucha demasiado alto con respecto a la musica. Esto ocurre en Mister, en cambio en mist parece que está todo correcto (al menos con el core antiguo de mist que estoy corriendo)

**Comment by jotego** [comment]
stairs: regression introduced in a7c531f

**Comment by jotego** [comment]
Stairs are visible in simulation: `jtsim -inputs -video 510 -w 490` in 20824ee6
[sim_inputs.zip](https://github.com/jotego/jtcores/files/14906787/sim_inputs.zip)

![frame_00499](https://github.com/jotego/jtcores/assets/1863036/129ff1df-8a69-4feb-8a2a-bba09f27ad7e)

**Comment by jotego** [comment]
fixed
