### ISSUE TITLE
analogue pocket  cps core  issues

### ISSUE THREAD

**Issue by sonicteam77** [jotego/jtcores#590]
When loading the Japanese version of CPS ROM, the DIP SWITCH option disappears in the core settings menu, and Allow to continue is turned off.

**Comment by jotego** [comment]
Could you give more details? Which game are you trying to load?

**Comment by sonicteam77** [comment]
Thanks for your reply. When I load the Japanese version of the CPS game US Navy, I can't see any CPS setting options in the core options, such as difficulty adjustment, screen flip and other DIP SWITCH settings. But these options are available when loading the world version CPS game. And the game's allow continue is also turned off.

**Comment by sonicteam77** [comment]
Another problem is that the Japanese version of the CPS vertical shooter 1941 and varth screens are not rotated for the analogue pocket, but the screen orientation of the us version of the game is correct.

**Comment by sonicteam77** [comment]
Thank you very much for your reply. I have solved this problem. Just copy the files in the alternative folder in PRESETS.

**Comment by jotego** [comment]
I'm glad you figured it out
