### ISSUE TITLE
Stretch CRT width doesn’t work on Pang/Robocop/Rastan cores analogue pocket 

### ISSUE THREAD

**Issue by ruffianes** [jotego/jtcores#593]
Stretch CRT width function doesn’t work on Pang/Robocop/Rastan cores analogue pocket.

**Comment by jotego** [comment]
Does it work in any core at all? It might be incompatible with the Pocket dock.

**Comment by jotego** [comment]
How are you exercising the stretch? It is not an option of the core...

**Comment by ruffianes** [comment]
Hello, the option is available on all cores together with the integre +. Before the last cores update, this option worked.

**Comment by ruffianes** [comment]
In fact this function is available and works with all your cores, except the ones I mentioned. By the way, amazing work you do.

**Comment by jotego** [comment]
The issue title says _Analogue Pocket_. Are you sure you don't mean _MiSTer_?

**Comment by ruffianes** [comment]
Sure. The issue is on analogue pocket.

**Comment by espiox** [comment]
“Stretch CRT Width” is a new option added in Analogue OS 2.1 (in January). It stretches (or contracts) the left/right edges of the CRT Trinitron Display Mode to fit the screen.

**Comment by jotego** [comment]
@rp-jt, please check out how this _stretch CRT width_ option works on the Analogue Pocket test the case described in the issue.

**Comment by jotego** [comment]
It seems like the option works by stretching the image but without cropping it. On the mention cores, stretching it so the image takes the whole screen would imply cutting off some of the left and right edges, so the Analogue Pocket ignores the setting.
