### ISSUE TITLE
tnzs schematics: sound signal path

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#595]
@skutis,  the sound signal path shown in TNZS schematics is a bit different from the three other ones we have in the kiwi/sch folder.

- R20 is 10 (tnzs) vs 8.2k (others)
- R17 is 330 vs 6.2k

Could you check it, please? By the way, R29 would look better if it was hanging down, so the GND symbol is at the bottom. Having it at the top makes it look like a supply.

Thank you

![image](https://github.com/jotego/jtcores/assets/1863036/4c4e429a-6d40-4e52-9190-4e198f640fba)

**Comment by skutis** [comment]
The resistor values are correct. Unless has been tampering with my PCB. It does not look like that though.

**Comment by jotego** [comment]
Thank you
