### ISSUE TITLE
Side Arms - Hyper Dyne - Glitches on Backgroud Sprites

### ISSUE THREAD

**Issue by Zichio** [jotego/jtcores#603]
Hi,

I have noticed that in "Side Arms - Hyper Dyne", there are some glitches on backgroud sprites (buildings/mountains).
Can be seen in the first Level, tested on MiSTer and Pocket. Shows up as some glitched lines/spots.

Did some testing on Pocket, and it seems that rbfs before "Feb 16, 2024" in JTBIN is OK.
Every version i tested after this point seems to show the issue, might have something to do with the convertion to mem.yaml on "Feb 27, 2024".

Thanks for all the great work :)

**Comment by jotego** [comment]
Thank you. This is fixed and will be released in the next update.
