### ISSUE TITLE
Unable to load cartridges in NGP Analogue core

### ISSUE THREAD

**Issue by dji85** [jotego/jtcores#629]
Since the last few updates the function to load cartridges on the NGP core for Analogue Pocket does not work. After going through the NGP initial setup menu (language selection and setting time) and arriving at the NGP menu, from here in past versions you could load a cartridge from the Analogue menu. In the latest version this does not work, and you end up back at the NGP menu screen. Core version is 274dbaf and Pocket is running OS v2.2.

**Comment by jotego** [comment]
Are you using the "virtual power button" to turn off the NGP before inserting the cartridge and then back on?

**Comment by thunder-rabbit** [comment]
as soon as you get home I will try it--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.04.24, 11:47 schrieb JOTEGO ***@***.***>:

   
  Are you using the "virtual power button" to turn off the NGP before inserting the cartridge and then back on?

**Comment by thunder-rabbit** [comment]
Hi Jotego,I have to go this waystart NGPChoose a RomSettingsChoose a RomRESETRESETNow it works but not all Games (Metal slug)RegardsSaschaAm 22.04.24, 11:47 schrieb JOTEGO ***@***.***>:

   
  Are you using the "virtual power button" to turn off the NGP before inserting the cartridge and then back on?

**Comment by jotego** [comment]
I am able to operate it, but the initial cartridge selection is ignored. If you boot up, then select a game using Analogue's OSD menu, and then turn off and on the core using the _virtual power_ button, the cartridge loads correctly.
