### ISSUE TITLE
Pantalla negra Super pang

### ISSUE THREAD

**Issue by Kaligulin** [jotego/jtcores#631]
Buenas, con el ultimo core jtpang al lanzar el super pang world hace la comprobación de ram ok 8 mhz original board y se queda pantalla negra o reiniciando en bucle. He borrado los mra la rom y el core sin solución, la única solución que encontré fue sustituir el core por uno anterior.
Saludos.

**Comment by jotego** [comment]
Prueba a borrar los archivos de configuración. A veces se corrompen e impiden al core arrancar bien.

**Comment by Kaligulin** [comment]
Hola, borrado los archivos de configuración y sigue el mismo problema, la solución la he encontrado al borrar los archivos nvram.
Gracias, por el soporte, lo replicare en el telegram de mister en español para futuros .
Saludos.

**Comment by jotego** [comment]
Gracias por la información. Me alegro de que lo pudieras solucionar.
