### ISSUE TITLE
shouse: Button names

### ISSUE THREAD

**Issue by Toryalai1** [jotego/jtcores#636]
The Namco system 1 games currently have "button 1" and "button 2" button labels.
Looking online, I can see that the cabinets had proper names. For example, Dragon spirit button labels are "Fire" and "Bomb".
https://www.flickr.com/photos/10707024@N04/34681730884

**Comment by jotego** [comment]
@jtmiki, edit the button names around line number 21 of this file https://github.com/jotego/jtcores/blob/master/cores/shouse/cfg/mame2mra.toml

**Comment by jtmiki** [comment]
I edited the button names. 
**Pro yakyuu world stadium** has three buttons to control.
**Face off** and **Pistol daimyo** have two functions on one button. A long press or repeatedly presses changes the type of shot.
Commit: c53a486

**Comment by jtmiki** [comment]
All of edited button's names showed up well on the define buttons of each game.
Commit: d9bda02

**Comment by jotego** [comment]
Maybe some buttons are swapped:

![image](https://github.com/jotego/jtcores/assets/1863036/aff9fa21-1a8e-405b-ba08-582933a98f5c)

**Comment by jtmiki** [comment]
Button's names of some games were swapped. I corrected them.
Commit: 579392f
