### ISSUE TITLE
Shouse: sounds strange (MiSTer)

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#641]
Following games all I can hear is bass, probably because one of the instruments is broken.
- [x] Marchen Maze
- [x] Rompers (music sounds bad)
- [x] Bakutotsu (shoot sound missing, coming from CUS30)
Commit: c53a486

**Comment by jotego** [comment]
This is probably related to #656

**Comment by jotego** [comment]
@jtmiki try to identify which sound channels are affected following the [debug instructions](https://github.com/jotego/jtcores/blob/master/modules/jtframe/doc/debug.md).

shouse channels:

- 0: FM (JT51)
- 1: PCM
- 2: CUS30

**Comment by jotego** [comment]
The sound waveform was read from the wrong channel. The noise implementation was incomplete. This needs more testing as there might be other problems, but the ones I opened the issue for are solved.
