### ISSUE TITLE
DV1 for RT4K, CPS 1 & CPS1.5 cores doesn't work.

### ISSUE THREAD

**Issue by mhmetalheart** [jotego/jtcores#642]
main mister: 240331
JT cores: ALL in 240426
dual sdram
ini set correctly.
So, I tested a lot of cores. EXCEPT only the CPS 1 and 1.5 cores doesn't work (no signal), even the 1942 works fine. 
I deleted the cfg files also. Updated all, also. Even use a new & clean SD card to rebuilt all. Asked my friend give me his ini to try again. Doesn't work... 
Anything I can do now? Please help.

**Comment by jotego** [comment]
I do not really know enough of RT4K to understand your problem but I do know that people are using it successfully with the all JT cores. Could you try asking in either my Discord server or MiSTer's?

Thank you
