### ISSUE TITLE
s18: button names

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#644]
Please add button names for SEGA System 18 games [here](https://github.com/jotego/jtcores/blob/master/cores/s18/cfg/mame2mra.toml)

**Comment by jtmiki** [comment]
I added button's names of most of the games.
I can't find **Pontoon** in the SEGA System 18.
I need time to find out the button name of **Where's Wally**. 
Commit: 65e99cb

**Comment by Toryalai1** [comment]
>  I need time to find out the button name of **Where's Wally**. Commit: [65e99cb](https://github.com/jotego/jtcores/commit/65e99cb066bc9bd0915914da33d56fc19c00bb94)

Where's Wally uses one button which is called "Confirm". Found it here: https://dl.vgmdownloads.com/soundtracks/wally-wo-sagase-system-18-arcade/W1.png

**Comment by jtmiki** [comment]
Thank you for the advice.
