### ISSUE TITLE
is core_mos 7 bits in MiST?

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#646]
There is this old note in [osd.md](https://github.com/jotego/jtcores/blob/master/modules/jtframe/doc/osd.md):

> Note that core mod is only 7 bits in MiST.

Is this still the case or can we use the whole byte?

**Comment by gyurco** [comment]
It's still 7 bits. It was introduced at the beggining of the multi-game cores, maybe it needs re-thinking.

**Comment by jotego** [comment]
Thank you. Let me know if it ever grows up to 8 bits.
