### ISSUE TITLE
jtframe_hsize: adjust HS location 

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#653]
jtframe_hsize is used on MiSTer to squeeze the video width, so it fits on the CRT. The image gets narrowed correctly, but also gets shifted to the left. 

This happens because the left horizontal blank time becomes shorter. 

Fix this module so the left horizontal blank is stable, and the image start position does not vary. Or, make the blank larger so the image center is stable.

**Comment by jotego** [comment]
framework preparations done in b506bd37

**Comment by rp-jt** [comment]
Completed in bc076008
