### ISSUE TITLE
jtframe_hsize: center image horizontally

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#661]
When the horizontal scaler is enabled, the image shifts to the left as it gets squeezed. It should remain centered.

This requires a change limited to the jtframe_hsize module.

**Comment by rp-jt** [comment]
Fixed in [effdfa4](https://github.com/jotego/jtcores/commit/effdfa4c78a7efaaf2eccc48fd667a52701c73e5)

**Comment by rp-jt** [comment]
Fixed in 5e35aa8e92570fc78a269c136e233e99d76ee3be
