### ISSUE TITLE
Parodius Da - Incorrect Button Mapping when using DB15 Joystick?

### ISSUE THREAD

**Issue by JuJuden** [jotego/jtcores#666]
Thanks for this amazing core!

When using an original NEOGEO Arcade Stick with a DB9 > DB15 splitter from Antonio Villena, the button mapping works as follow:
A - Shoot
B - Missile Bell Power
C - Power Up

According to the [Operators Manual](https://www.arcade-museum.com/manuals-videogames/P/Parodius.pdf), it seems the correct mapping should be: 
A - Power Up
B - Shoot
C - Missile Bell Power

I think the latter is also more consistent with other Gradius / Parodius games.

**Comment by jotego** [comment]
Fixed in cf8f884

**Comment by JuJuden** [comment]
Just wanted to confirm it's now working fine. Thank you for fixing it.
