### ISSUE TITLE
aliens,s16,s16b,shouse,simson: DDR load on MiSTer

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#669]
Fast DDR load has been enabled for some cores. Check that they boot up correctly with the latest build. One game per core is enough.

- [x] aliens
- [x] s16
- [x] s16b
- [x] shouse
- [x] simson

**Comment by jtmiki** [comment]
I checked each game of these cores and booted up correctly.
commit: 299bb31

**Comment by Toryalai1** [comment]
s18 missing fast ddr load

**Comment by jotego** [comment]
> s18 missing fast ddr load

Thanks. It will be in the Friday release.
