### ISSUE TITLE
[Enhancement] Rastan Core: Support for Rainbow Islands?

### ISSUE THREAD

**Issue by uchristo** [jotego/jtcores#671]
Is it possible to support Rainbow Islands with Rastan RBF? As far as I understood, they both run on the [same Hardware](https://www.system16.com/hardware.php?id=650)

**Comment by jotego** [comment]
This is in the road map indeed. There is work already done in this front. Thanks for the reminder. I close the issue as we will not track it in this specific issue. But the answer is positive.

**Comment by uchristo** [comment]
Great news! Thank you so much for your continous work!
