### ISSUE TITLE
The Simpsons doesn't play The Simpson theme when...

### ISSUE THREAD

**Issue by bnice** [jotego/jtcores#673]
The Simpsons doesn't play The Simpson theme when core starts and title sequence graphics are playing...

**Comment by jotego** [comment]
You can enable it in the service menu. Press F2 to enter. Save the settings after that so it stays like that on the boot.

**Comment by bnice** [comment]
Hi Jotego,
Thanks for this. Just wondering where I could have found about F2? I did reassigning buttons to see if I could find any useful buttons but the service menu doesn't appear there.
