### ISSUE TITLE
1942: graphic bug with Boss (big airplane)

### ISSUE THREAD

**Issue by Lmn-San** [jotego/jtcores#678]
Every 8 levels there is a boss appearing. With vertical lines missing.
![IMG_5072](https://github.com/jotego/jtcores/assets/61054969/5088088c-2258-4a2e-9e71-9616e1c25448)

**Comment by jotego** [comment]
Could you please share a snapshot of your DIP settings?

**Comment by Lmn-San** [comment]
Here it is. (Playing on MiSTer)
![Uploading IMG_5078.jpeg…]()

**Comment by jotego** [comment]
Well, believe it or not, this is a genuine bug but it only happens with that flip setting. Toggle the flip setting, reset the machine and it will be gone.

It is the same issue that also causes this screen if you wait long enough in attract mode:

![20240527_173641-screen](https://github.com/jotego/jtcores/assets/1863036/adf96a0c-2b23-447f-9c80-aae0a46cea0a)

The CAPCOM logo appears split. 

I could fix it, but the real hardware was shown to behave this way, so I'm leaving it. The thing we can do is to have the good flip setting as default. If you play through HDMI, rotating the video, there is no penalty in turning flip on.

**Comment by Lmn-San** [comment]
Thank you. I didn't knew that was a genuine bug.
By turning the flip on it worked as you mentioned.
