### ISSUE TITLE
Workaround for MiSTer controller limitation: 3P/3K

### ISSUE THREAD

**Issue by Firehawke** [jotego/jtcores#679]
If using an arcade stick, the lack of easy mapping for CPS1/2 3P/3K isn't a huge problem, but on almost any other kind of controller it can rapidly turn into a major problem. MiSTer will let you do alternate mapping, but it won't let you do three buttons on one.

Please consider adding optional dedicated 3P/3K inputs.

**Comment by jotego** [comment]
Sorry this issue got overlooked.

I think this should be handled by the FPGA platforms. Particularly because the core already has 8 buttons (6 for action plus credit and start). Please try to get this implemented directly in the MiSTer platform and all cores will benefit from it.

Thank you
