### ISSUE TITLE
Music on radio screen of Out Run

### ISSUE THREAD

**Issue by bnice** [jotego/jtcores#680]
Hi,

First thanks to Jotego for answering the last time I opened this. However, I couldn't find any option under the system menu (F2) to turn on music, on the radio screen, where you select the music you want to play in game as suggested.

I did find the option to turn on the attract music for The Simpsons in the system menu (F2), so thanks for that. I would like to know where I would of been able to find out this for myself as the system menu key is not one you get prompted reassign like the buttons like other up, down, credits, etc. That way I won't have to bother you again :-) .

Ben

**Comment by terminator2k2** [comment]
not all versions seem to play the music on the radio audio selection screen, this is the same in mame, so looks like that is just how it is.

**Comment by bnice** [comment]
Thanks Terminator2k2. It does make hard to know which track to select when you can't hear them though.

**Comment by bnice** [comment]
Cheers Terminator2k2 the Deluxe version you mention plays the tunes on the radio screen.

**Comment by bnice** [comment]
Closing issue
