### ISSUE TITLE
NGPC on Analogue Pocket 

### ISSUE THREAD

**Issue by disruptityourself** [jotego/jtcores#683]
I've been following the Neo Geo pocket core for a while and supporting it's development. I just installed the most recent update and I can no longer navigate the BIOS. None of my button presses register.

**Comment by jotego** [comment]
Thank for your support. From your description, it looks like you are missing the latest beta file. If you stopped being a Patreon, you can go back to the former core version which will still work with your old beta file.

In general, if you stop being a Patreon you can keep the beta cores working if you do not update them. The beta key changes only once every many months (last time was 5 months). The current list of cores in beta phase is [here](https://github.com/jotego/jtbin/wiki)

I am still missing the full color implementation. That is holding that core in beta longer than I'd like to.
