### ISSUE TITLE
s16/s18: enable NVRAM saving

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#700]
Saving NVRAM will save high scores. Look into adding this feature. May require moving the system RAM to BRAM.

Not all games seem to save high scores, but some do.

- [x] S16
- [x] S16B
- [x] S18
- [x] shanon
- [x] OutRun

**Comment by jotego** [comment]
Preliminary work done in fea40295. 

Saving works but it tends to crash the main CPU as it block access to the RAM while saving. Restoring does not work. Not clear why.

It is better to re-start from the master branch moving the first 16kB of work RAM to BRAM in mem.yaml. Then saving and loading is taken care of by the framework.

**Comment by jotego** [comment]
s16/s16b NVRAM saved support in 49052f05

**Comment by jotego** [comment]
shanon/outrun NVRAM saving support in 33ae343d. OutRun does not seem to load it back correctly or at least the bookkeeping information is not stored well.

**Comment by jotego** [comment]
S18 NVRAM implemented in 99cd89d0

**Comment by theenemy-thd** [comment]
So outrun still doesn't save hi scores? I notice in alternative roms it supports the enhanced version of outrun which does save high scores but on mister it doesn't seem to show any of the enhanced options/settings
