### ISSUE TITLE
Sync Issues on PVM/Consumer CRT - TMNT, Simpsons, Splatter House

### ISSUE THREAD

**Issue by HawkeyeRetro** [jotego/jtcores#702]
I have a 6.0 I/O board and have noticed issues with sync for the TMNT, Simpsons, and Splatter House cores. I have no other sync issues with any other cores for arcades or consoles. 

My output is via component cables. I have tried these cores on two different monitors with the exact same result. One is a Toshiba A model (consumer CRT) the other is a Sony PVM 14m4u. 
![IMG_5501](https://github.com/jotego/jtcores/assets/172640919/a5f41228-4691-4325-9cc6-63c431260bb3)

![IMG_5503](https://github.com/jotego/jtcores/assets/172640919/7481037f-7ed5-4eac-80e5-a498524653a6)

https://github.com/jotego/jtcores/assets/172640919/dd917a58-331a-4ec9-8ecf-37631363f1e3

https://github.com/jotego/jtcores/assets/172640919/24b17016-d899-4065-a923-b47fcc8a3b08

**Comment by jotego** [comment]
This is common for games that produce overscan images. It does not happen on our test equipment but as I said, it is not unsual. This is similar to #692. It looks like the PLL circuit in your monitors needs a bit more time to lock the horizontal synchronization signal. Hence the first few lines show that effect.

If you move the vertical image position up using the OSD menu, the PLL will get more time to lock and the top of the image will improve. But, it will push the image down. We are looking into adding more advance HS customization options in the OSD menu, but it will still not be enough for all monitors and cores. Some monitors just not lock certain frequencies in time to display the active video part of the signal.

I think replacing the capacitors on these monitors may have a chance of improving the PLL performance. Particularly, around the supply decoupling and the horizontal synchronization circuit.

**Comment by HawkeyeRetro** [comment]
Thank you for the reply. I have attempted to “push” the image with the OSD options but it oftentimes just makes the image worse. It is interesting that the exact same issue arises on two different monitors. Do you think this could be an issue with the 6.0 DAC? Thanks!
