### ISSUE TITLE
CPS1 UN Squadron/Area 88 Explosion sounds issues

### ISSUE THREAD

**Issue by Left-Empty** [jotego/jtcores#711]
Hello,

I was playing Area 88 today and the gunfire sounded strange, while the explosions didn't sound like explosions in the current version anymore but more like farts, if you pardon my saying!
Cheers!

**Comment by jotego** [comment]
I cannot hear anything odd about them. You can try changing the PCB type in the DIP switches menu. That will change the type of filter applied to the PCM sound. MAME seems to have a similar sound anyway.
