### ISSUE TITLE
Thundersticks ls-30 support

### ISSUE THREAD

**Issue by Firehawke** [jotego/jtcores#712]
The SNK cores recently got [Thunderstick's LS-30](https://thunderstickstudio.com/products/grs-super-joystick) support using keyboard keys for the rotational switches (left/right arrow for player one, C/V for player two), so any chance you could maybe add that to the Midnight Resistance/Heavy Barrel cores?

It'd work best as an optional switch so the special keybinds don't interfere with playing these games keyboard-only.

**Comment by jotego** [comment]
These joysticks already work on JT cores setting them in the mouse mode.
