### ISSUE TITLE
Pocket Analogizer: Vertical line of each letter is missing

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#740]
I have tested all cores on Pocket Analogizer connects on TV.
There are three cores in which the vertical line of each letter is missing.
I attach several screenshots of the problems that you can compare the Pocket version and the TV version.

**slyspy: Secret Agent** 
Pocket version
![S Agent Pocket](https://github.com/user-attachments/assets/87cbca84-f4bd-48d6-920c-8711d0e03f84)
TV version
![S Agent TV](https://github.com/user-attachments/assets/f3da90a2-b03c-4255-8c83-de6063d17824)

**track: Track & Field**
Pocket version
![Track Field Pocket](https://github.com/user-attachments/assets/29f4e626-0c71-40b1-ad4b-6b017aa99d51)
TV version
![Track Field TV](https://github.com/user-attachments/assets/2f9e3e20-72e7-468e-80c9-150b79ab7704)

**shouse: Dragon Spirit**
Pocket version
![D Sprit Pocket](https://github.com/user-attachments/assets/75a5a963-912b-40b3-b81d-85668756873a)
TV version
![D Spirit TV](https://github.com/user-attachments/assets/877534d9-a782-4013-b53f-dd96d8574191)

Commit: 7c233d7

**Comment by jotego** [comment]
already completed
