### ISSUE TITLE
Outrun graphic glitch on left side

### ISSUE THREAD

**Issue by theenemy-thd** [jotego/jtcores#744]
I have noticed an issue on the graphics on the left hand side especially on the stage with stone arches ... it happens to the left but also bad above on the top of the arch that goes the full length of the screen but again only on the left
![20240728_111820](https://github.com/user-attachments/assets/0b6b8b68-a0dc-425b-8333-84ae5ebbce65)

**Comment by jotego** [comment]
Thanks for reporting it. This is due to a limitation in how many points can be drawn per line without using a frame buffer for the sprites. There is no fix planned.

**Comment by theenemy-thd** [comment]
something that can be fixed on more powerful fpga?

**Comment by jotego** [comment]
Particularly, one with more RAM chips

**Comment by theenemy-thd** [comment]
You mean on board ram that has a higher access speed?
