### ISSUE TITLE
SSF2T(CPS2): Cammy stage: visual artefacts in the lowest line of the aurora in the sky

### ISSUE THREAD

**Issue by oneoogeoo** [jotego/jtcores#746]
The problem has been around for a long time: visual artifacts in the lowest line of the aurora in the sky at the cammy stage in Super Street Fighter II Turbo.

Unfortunately very difficult to photograph, as it occurs e.g. when jumping. Not even in pause mode, because some things are displayed incorrectly. But when you play the stage, you can see it immediately.

Maybe you can fix that. I would be very happy as it is one of my all-time favorites.

**Comment by paulb-nl** [comment]
The artifacts look the same on the original PCB:
https://www.youtube.com/watch?v=HJZSstDbuBU

**Comment by atrac17** [comment]
@paulb-nl is correct, this is normal behavior for Cammy's stage. DeeJay's stage glitching and Fei Long's stage glitching is also a hardware bug.

**Comment by jotego** [comment]
> @paulb-nl is correct, this is normal behavior for Cammy's stage. DeeJay's stage glitching and Fei Long's stage glitching is also a hardware bug.

Thank you
