### ISSUE TITLE
Exed Exes only show colored boxes

### ISSUE THREAD

**Issue by dfilskov** [jotego/jtcores#749]
Its audio works but the video signal looks like this:

![Screenshot_20240802-181934~2](https://github.com/user-attachments/assets/6a93a2d7-0e22-4b68-a068-39cf658112a9)

**Comment by dfilskov** [comment]
Oh and as with all jt cores that rotates the video signal integer scaling is broken - it's applied _before_ the rotation instead of _after_ the rotation. 

When not rotated integer scaling works.

**Comment by jotego** [comment]
Delete your Arcade folder and run update_all again. I think you're running an old version of the rbf file with a new version of the MRA file

**Comment by dfilskov** [comment]
Thanks! I already did but I can double-check

**Comment by dfilskov** [comment]
You were right - sorry.

I had two mra files and was trying the wrong/old one.
