### ISSUE TITLE
CPS-2 Dimahoo - scandoubler/integer not working

### ISSUE THREAD

**Issue by dfilskov** [jotego/jtcores#751]
Like on all JT cores that rotates its video signal integer scaling does not work. I think Integer scaling applied before the rotation instead of after (or it could be becuase I use 1920x1920 and the scaling can't deal with square resolutions).

Scandoubler CRT scanlines don't work either.

Please check this video to see for yourself that scanlines does not appear:

https://github.com/user-attachments/assets/5a89e83c-8648-4d9c-b32b-be545919a2d8

**Comment by jotego** [comment]
Duplicated in #726
