### ISSUE TITLE
circus charlie core

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#754]

**Comment by jotego** [comment]
executed in b23c406ba6a8aff0c786c008c49316f49bf2a282

**Comment by theenemy-thd** [comment]
There seems to be an issue with graphical glitch at the top of the screen when screen flip is used in dip switches. It happens on the titlepage 
![20240901_094921(0)](https://github.com/user-attachments/assets/10525b70-96bf-48a8-b31a-761d3d50c707)
![20240901_095016(2)](https://github.com/user-attachments/assets/6740758a-1588-4da5-81a5-8b2efe8c712c)
![20240901_095016(0)](https://github.com/user-attachments/assets/30d89fc6-d901-4126-9d93-a3d0c7687569)
![20240901_095018(1)](https://github.com/user-attachments/assets/0dc98ae4-0f33-43b2-9879-d48e6d8bb0a4)

**Comment by jotego** [comment]
I guess the problem is the stars going over the score? Thanks for reporting it. 

The tent going black is normal, though.

**Comment by theenemy-thd** [comment]
Regarding the tent going black on thr attract screen ... at the time I re ran it non flipped and I didn't see it go black so very strange. I will test it again on friday
