### ISSUE TITLE
 Yie Ar Kung-Fu

### ISSUE THREAD

**Issue by AnotherPocket** [jotego/jtcores#763]
The last two updates do not work for me. It loads to a screen of the character '0', which I assume is the arcade checks. It never exits this screen, no matter the length of time I wait. If I put back on the old Core files, the ROM works as expected.

**Comment by jotego** [comment]
Regenerate your ROM file from the latest MRA.

**Comment by AnotherPocket** [comment]
Thank you, that worked perfectly.

Is there a way to download all of the .mra files at one time?

**Comment by AnotherPocket** [comment]
Thank you. That worked perfectly. I appreciate your help.
