### ISSUE TITLE
ngp: Test result CPU Test by Judge (For reference)

### ISSUE THREAD

**Issue by wwark** [jotego/jtcores#771]
Result of CPU Test by Judge
![20240817_115029-CPU Test by Judge_ (PD)](https://github.com/user-attachments/assets/6aeaef2b-7745-4409-aa54-bfd4adf8e751)

Seems to have an issue with the core

Thanks,

**Comment by jotego** [comment]
Thank you. I am aware and I have reviewed the DAA test several times. At this point I doubt of the test.

**Comment by wwark** [comment]
But What is the test result on real hardware ? Is it the same ?
Thanks,
