### ISSUE TITLE
riders: some objects appear outside the frame

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#772]
Scene 10. Checkout the fort at the bottom left

![frame_00002](https://github.com/user-attachments/assets/1e48cae0-d5fc-44bb-b87b-8fbf0b640f99)

**Comment by rp-jt** [comment]
Same issue causing priority problems in the borders of some sprites.
See scene 7:

![7](https://github.com/user-attachments/assets/3a849f7c-3cf6-4857-8fa5-71c1d169ff25)

**Comment by rp-jt** [comment]
Fixed in cc19c5b87f42164c6044be36af81d5759280278d
