### ISSUE TITLE
Galaga 88 flip screen not saved

### ISSUE THREAD

**Issue by spotUP** [jotego/jtcores#778]
galaga 88 (namco system 1) has an option to flip the screen in the testmenu, but the option isn’t there in the osd dipswitch settings. If i flip the screen in the test menu it isn’t saved, could this be fixed? 🙏

**Comment by jotego** [comment]
You have to manually select **Save settings** in MiSTer's OSD menu. Only DIP switch changes are saved automatically by MiSTer. In this case, Galaga is saving the flip configuration to the system NVRAM. MiSTer will copy that memory when you *save settings*

**Comment by jotego** [comment]
You can test the files compiled for the new MiSTer framework [here](https://github.com/jotego/jtcores/actions/runs/10547910159/artifacts/1851963305), in case this is a compatibility problem with the latest mister version.

**Comment by spotUP** [comment]
Huh. It works now. Sorry for the trouble!
I tried many times and was sure i saved the settings, but it seems not. Really sorry for your time spent on this.
