### ISSUE TITLE
Wonder Boy III: Monster lair - Boss don't appear

### ISSUE THREAD

**Issue by Duchemole** [jotego/jtcores#796]
when reaching bosses (I've checked only the 2 firsts), you can see just their shape, they're black, but are not visible

**Comment by jtmiki** [comment]
I've tested it until Round 4 with today's compile all and there was no problem. 
The bosses are visible.
Commit: 215d165

**Comment by Duchemole** [comment]
Hello
Terribly sorry about that, my romset might probably be responsible
Next time, I'd better try replacing it before making you wasting your time
My humble apologies
Thanks a lot for your reactivity

________________________________
