### ISSUE TITLE
S18: Alien Storm music sounds strange

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#798]
The intro part of music sounded well.
Music sounded strange from the 1st stage.
The balance between the main sound, sound effects and attack sounds sounds strange.
Either the attack sounds are a little too quiet, or the high-pitched metal sounds of the main sound are too prominent and unbalanced.

Commit: 215d165

**Comment by jotego** [comment]
I think it sounds as peculiar as in MAME
