### ISSUE TITLE
Vigilante Color Bug

### ISSUE THREAD

**Issue by MaskedNinjaYT** [jotego/jtcores#801]
Stage 5 Background color bug.

![erererrewq](https://github.com/user-attachments/assets/6442ade4-77d1-4505-b17b-e726977ebea2)
![Vigilante_Background_Color_Bug](https://github.com/user-attachments/assets/1c10644e-4e9c-455c-9fda-4c8f7786b6e7)

**Comment by jotego** [comment]
This looks like a problem with ROM zip. One the bit planes seem missing. Can you check your zip file, please?

**Comment by MaskedNinjaYT** [comment]
This is inside the zip:

tbp24s10_7a.ic52
vg_a-4d-.ic26
vg_a-5j-.ic37
vg_a-8h-e.ic55
vg_a-8l-a.ic57
vg_b-1b.ic1
vg_b-1d-.ic2
vg_b-1f-.ic3
vg_b-1h-.ic4
vg_b-4f-.ic34
vg_b-4j-.ic35
vg_b-4m.ic38
vg_b-6k-.ic61
vg_b-6l-.ic62
vg_b-6n-.ic63
vg_b-6p-.ic64
vg_b-8r.ic90

**Comment by jotego** [comment]
I can see it too.

**Comment by jotego** [comment]
- none of the values for scr2col displays the right image
- moving the CPU to clk48 did not make a difference

The problem can be reproduced with scene 2 in commit f6e38d9e

`jtsim -s 2`

Generate the sdram files by loading the game normally with `jtsim -load`. In this game, `jtutil sdram` will not get the transformation done in the game module.

**Comment by jotego** [comment]
- the palette RAM content is the same as in MAME

**Comment by jtmiki** [comment]
I have tested it and there are still color bugs.
![20240918_113959-screen](https://github.com/user-attachments/assets/fcc635e3-f1ed-4802-ae0b-4a8d7c9d3e5c)
Commit: 047ccd4

**Comment by jotego** [comment]
The color split is visible in MAME's GFX view

![image](https://github.com/user-attachments/assets/947b3057-b83e-431d-aeb5-c6e9ef29e714)

**Comment by jotego** [comment]
pin 13 of the palette IC was assumed to be related to the score row, but it simply marks the middle of the screen. Fixed in 34d2b4c

![image](https://github.com/user-attachments/assets/3ccdce29-a3b5-45a0-96d0-f533010e2fe6)

It works now:

![frame_00001](https://github.com/user-attachments/assets/1fdad22f-57bf-443a-9414-7093c21c7577)
