### ISSUE TITLE
wwfss: button setup

### ISSUE THREAD

**Issue by jtmiki** [jotego/jtcores#805]
User question:

> I am confused about the button setup. On the title screen is references Button A (1P vs CPU), B (1P vs 2P) and C (1P/2P vs CPU). So far, I have only been able to get Start to do anything (regardless of number of non-zero credits entered), appearing to be tired to Button A. In the button setup it references Right Attack, Left Attack and Jump. During game play, Ive only been able to notice (Left Attack) Punch and (Jump) Kick with no Jump (Right Attack doing nothing)... Am I just missing something? How do you start different game modes?

Commit: b89a709

**Comment by jotego** [comment]
Added button C in b2de62fcd
