### ISSUE TITLE
The Simpsons (jtsimson): Incorrect scaling and background colors in intro

### ISSUE THREAD

**Issue by BMF54123** [jotego/jtcores#813]
The scaling on the logo in the intro is very wobbly and the letters jump around a lot compared to both the original PCB and MAME. Footage of an original PCB can be seen here:

https://www.youtube.com/watch?v=Dy5ZWV35CMQ

You can also see that the "S" in "SONS" completely disappears for a frame or two right before it switches to the next scene:

![image](https://github.com/user-attachments/assets/487762b6-ddea-4a7a-bb7a-7b8c7c94bc88)
![image](https://github.com/user-attachments/assets/7d80368f-bd40-4290-9ad7-868b7e2e9aba)

Additionally, the background color seems to be much too dark; it should be the same shade of blue as the following scenes. This also affects the background of the Konami logo, which is white on a real PCB:

![image](https://github.com/user-attachments/assets/9dc70546-97d8-4b1c-8b60-eb2b23a7b5bc)

I assume the logo scaling issues are related to various other sprite scaling issues that have been reported in this and other Konami cores.

**Comment by rp-jt** [comment]
The problem with the characters was solved by increasing the buffer size for drawing the objects

I have put the problem with the background colors on a separate issue (#832)
