### ISSUE TITLE
NeoGeoPocket - (RBF mode) - Control not working after loading the game

### ISSUE THREAD

**Issue by wwark** [jotego/jtcores#818]
How to reproduce the case:

- Launch the RBF NeoGeoPocket
- Click power button to have white screen
- Load the game on the OSD
- Boot screen starts to process but the controls on the gamepad doesn't work

Thanks,

**Comment by jotego** [comment]
It may have some sensitivity to the FPGA/memory previous state (like playing another core before?). After many tests, I have only seen it happen once.

I'll keep it in my mind but not as an open issue.

Thank you

**Comment by wwark** [comment]
Thank you :)
