### ISSUE TITLE
jcps: no way to rotate screen?

### ISSUE THREAD

**Issue by rmcmelo** [jotego/jtcores#828]
In the JCPS core, Mercs is rotated 90º clockwise, but there is no option in "Core Settings" to rotate. 
Furthermore, controls option doesn't appear to work,

I have Version dc4548b.

Thanks

Edit: I've discovered the problem. The issue happens because I renamed the JSON files. Is there any file I can edit in order to be able to rename the files?

**Comment by jotego** [comment]
JSON files in the Pocket are many and have deep connections between them. The Pocket firmware handles any small inconsistency in a poor way. So _tampering_ with them usually results in a broken core. You can consult Analogue's [documentation](https://www.analogue.co/developer/docs/overview) on these files.

If you simply want to rename the files, I think some Pocket updaters provide this feature.
