### ISSUE TITLE
s16b: Time Scanner - Flip Screen DIP switch does nothing

### ISSUE THREAD

**Issue by Thelypody** [jotego/jtcores#834]
Time Scanner (set 2, System 16B)
Running on MiSTer connected to a CRT TV via Analog IO board.

This vertical game displays by default on a horizontal analog display as rotated clockwise. The game features a DIP switch marked Flip Screen, however it appears to not be working. Enabling it produces no effect, instead of expected result of the image being turned counterclockwise on a horizontal display.
For reference, this DIP switch seems to be working in MAME.

**Comment by jotego** [comment]
Time Scanner uses a third DIP switch which was not connected. Fixed in 4bfc5ac
