### ISSUE TITLE
Xmen Konami missing echo effect.

### ISSUE THREAD

**Issue by Garagefreek** [jotego/jtcores#843]
Mame version still has problems with the sound and music in xmen but on fpga it’s sounds more accurate and very close to the pcb as far as I know it’s only missing the echo effect when the attract intro arrives at the title screen, the announcement of "X-Men" has an echo effect and the same missing echo effect from Professor X's "Go Save the City".

**Comment by Toryalai1** [comment]
This is a duplicated issue: https://github.com/jotego/jtcores/issues/842
Close this or the other down

**Comment by Garagefreek** [comment]
I tried to delete but couldn't it was uploaded by mistake.

**Comment by rp-jt** [comment]
I close this one and we can stick to #842 for this issue

**Comment by Garagefreek** [comment]
Thank you much appreciated.
