### ISSUE TITLE
paroda: Cat-boat reappearing horizontally

### ISSUE THREAD

**Issue by rp-jt** [jotego/jtcores#846]
In Parodius, at the end of the first stage, if you don't destroy the cat-boat, it will disappear through the left border of the screen.
The same boat reappears right after from the right (picture) before disappearing for good this time. 
Probably similar to #813 
![31](https://github.com/user-attachments/assets/6b79deaa-cf45-4e0f-83ee-a6328ce2327e)

**Comment by real-amano** [comment]
Maybe related to  #724 since the bell explosion sprite is a big one as well.
