### ISSUE TITLE
Xmen Konami sentinel mouth bug.

### ISSUE THREAD

**Issue by Garagefreek** [jotego/jtcores#847]
The giant sentinel has a vertical sprite gap in the centre of the mouth..
![image](https://github.com/user-attachments/assets/7114a3cf-c032-455c-9b4e-d3c4f31c537d)

**Comment by Toryalai1** [comment]
Should've been fixed by this change:
https://github.com/jotego/jtcores/pull/831

**Comment by Garagefreek** [comment]
I don't have a mister device yet I spotted this on YouTube a few days ago so I'm not sure?

**Comment by Toryalai1** [comment]
What video?

**Comment by Garagefreek** [comment]
Just go to YouTube and see for yourself there's a few full play through videos on xmen for the mister you'll notice the bug when you see it..

**Comment by real-amano** [comment]
Well. If the YouTube video is older than the fix it is not surprising that the bug is still there in it.

**Comment by Garagefreek** [comment]
That's great news! thank you for clarifying much appreciated..
