### ISSUE TITLE
jt1942 scores are misplaced vertically and wrap around to bottom of screen.

### ISSUE THREAD

**Issue by TrickoUK** [jotego/jtcores#858]
The placement of hiscores in both 1942 and Vulugs are split where while the scores are shown at the top of the screen, the majority of the text "1UP HISCORE 2UP" is wrapped and appears at the bottom of the screen.

This is with HDMI out, vertical orientation, see screenshot for example -

![20241029_064547-screen](https://github.com/user-attachments/assets/1a0d79b6-ba35-41dd-b5cb-3c095bd2bf03)

All works fine still, in terms of the scores updating, its just looks off.

**Comment by jtmiki** [comment]
I've checked from which core this problem started and it was from the 6th of September.
commit of 6/9/24 : dae97e2
On this date, when the game was activated, the screen went dark and only music was heard.
commit : 0af9818

**Comment by jtmiki** [comment]
On the 6 of September, the Compile All was activated seven times.
The game worked fine until commit : 4972fbc, but from commit : 5803857 the screen display changed to black.

commit: 0c115ef
