### ISSUE TITLE
wc: support for grid iron

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#867]
The game starts booting but gets halted at the grid screen (9e120b393). Pressing 1P&2P during boot goes through the test screen, which seems ok.

The game also has an LED display, according to MAME:

>Gridiron Fight has a LED display on the control panel, to let each player
>choose the formation without letting the other know.

**Comment by gyurco** [comment]
This is something about interacting with the sound CPU.
The main CPU doesn't get the expected value in the s2m sound latch, and goes to an infinite loop code path.

**Comment by gyurco** [comment]
I have the fix for Gridiron, however World Cup doesn't work even with clear master. Is it expected, or am I have something wrong?

**Comment by jotego** [comment]
World Cup has been running all day long. Regenerate the ROM files as I introduced an 8-byte header earlier today.

**Comment by gyurco** [comment]
Yeah, ROM regeneration worked. I'll post the fix for gridiron soon.

**Comment by jotego** [comment]
Thank you!

**Comment by jotego** [comment]
Thanks, gyurco. @jtmiki this issue is completed.
