### ISSUE TITLE
WWF Superstars low volume

### ISSUE THREAD

**Issue by konradpop** [jotego/jtcores#873]
core volume and global volume is max, the core has very low volume even with everything maxed out. Running mistercade v2, other cores are not effected by this.

**Comment by ZZZyeahZZZ** [comment]
I can confirm. For me, volume varies across all cores within 'reasonable' amounts, but the volume in WWF Superstars is basically zero. It is not just low, it is extremely extremely low.

**Comment by jtmiki** [comment]
We have tested it on MiSTer.
The volume is low.
If the volume is turned up to maximum, it can be heard, but the announcer's voice is still muffled and difficult to understand.
Commit : fe5f639
