### ISSUE TITLE
Speed Rumbler - Alt MRAs do not have properly balanced sound

### ISSUE THREAD

**Issue by Aquas77** [jotego/jtcores#88]
Currently (Set 1), the default MRA for Speed Rumbler is the only MRA that has proper sound balancing. The sound effects are really quiet on the alts.

**Comment by jotego** [comment]
Confirmed. The sets below have loud FM and quiet PSG channels. This is quite unusual as it shows either a hardware or software change in the main version of the game

- rushcrsh
- srumbler2
- srumbler3

**Comment by jotego** [comment]
This requires a bit of messing with the files for technical reasons:

- the core does not use mem.yaml, so adding a header to the MRA is a bit messier -but no big deal-
- the core sound comes from module _jtgng_sound_, which provides fixed gain settings at the moment and it is shared by other CAPCOM-compatible cores
- it may be worth doing #402 first

**Comment by jotego** [comment]
Fixed in #88
