### ISSUE TITLE
NeoGeo Pocket Color Core in Black and white, wont boot most color games.

### ISSUE THREAD

**Issue by douglie007** [jotego/jtcores#881]
This might be a setup issue, I renamed the NGP bios to boot.rom, I get to the setup the date but only in B & W.  I dont see much options to change anything, and dont see much of others showing the issues.

**Comment by jotego** [comment]
I think you may be trying to use the NGP core instead of the NGPC one. Note that on MiSTer, the NGPC core does not show up in the console menu (yet) but instead you have to look for it in Arcades/alternatives.
