### ISSUE TITLE
Using the keyboard to control Arcade games does not work

### ISSUE THREAD

**Issue by tarikalmashni** [jotego/jtcores#892]
I can define keyboard keys in the OSD just fine but when getting back into the game, no defined keys are being accepted.

Nothing happens. I can't use the coin or start button.

Tested in Super Street Fighter 2 Turbo, SSF2T New Legacy and Aliens.

**Comment by asturur** [comment]
Only defaults work for some reasons in aracde. So 5 for coins, 1 for p1 start, arrows and for buttons ctrl alt shift e and something else

**Comment by jotego** [comment]
Keyboard keys are hard locked to MAME's default keyboard. You can only remap controllers.

**Comment by tarikalmashni** [comment]
Thanks for clarification!
That's a big letdown. Is there no way around it? Other cores don't seem to suffer from this issue.

**Comment by jotego** [comment]
People connecting controllers to cabinets rely on this default mapping as many of these joystick-to-USB converters look like a keyboard interface.

I think this is the first request I have got to support remapping the keyboard since I started the project 5 years ago.

**Comment by tarikalmashni** [comment]
Fair enough.

I know I'm in a niche here but I've grown up playing Street Fighter on the PC with a keyboard and until now I'm still the most comfortable when playing fighting games on a keyboard.

**Comment by asturur** [comment]
i grew up with the keyboard too and indeed my go to stick has a right side arrow keys to compensate that.
All the hitbox players are just negationists of the keyboard.

Jokes asides i didn't know the other cores remap keyboard either, i thought it was not working at mister level
