### ISSUE TITLE
[Bubble Bobble] Not possible to enter credits on the Analogue Pocket

### ISSUE THREAD

**Issue by vanfanel** [jotego/jtcores#901]
Hi there,

For some time, after updating this core, I'm not able to enter credits anymore on the Pocket, no matter what button I push.

I also tried to reset the controls, deleted all the core config files, etc

**Comment by jotego** [comment]
Are you referring to the core credits?

**Comment by real-amano** [comment]
Or the Highscore initials?

**Comment by davewongillies** [comment]
I can confirm that the Bubble Bobble core doesn't have this problem on my Pocket.

@vanfanel try completely deleting the directories `Presets/jotego.jtbubl` & `Settings/jotego.jtbubl` then install the core again. Its probably left over files in the `Presets` causing the issue.

**Comment by vanfanel** [comment]
> Are you referring to the core credits?

I mean inserting coins.

**Comment by vanfanel** [comment]
> I can confirm that the Bubble Bobble core doesn't have this problem on my Pocket.
> 
> @vanfanel try completely deleting the directories `Presets/jotego.jtbubl` & `Settings/jotego.jtbubl` then install the core again. Its probably left over files in the `Presets` causing the issue.

Ah, yes, that fixed it, thanks! Closing this
